### ISSUE TITLE
[TS] useForkRef type definition is incompatible with null or specific type of html element

### ISSUE THREAD

**Issue by neolivz** [imbhargav5/rooks#1016]
**Describe the bug**

Type definition of `useForkRef` does not support null value to be passed as one of the ref. This is problematic as using with forwarded ref which can be null
```
    type ForwardedRef<T> = ((instance: T | null) => void) | MutableRefObject<T | null> | null;
```
There is no type safety check for making sure that the combined ref is used only on a particular type of HTMLElement, e.g HTMLButtonElement.

**To Reproduce**
Steps to reproduce the behavior
```
const Component = forwardRef<HTMLButtonElement, { callback: () => void }>(
  ({ callback }, ref) => {
    const [myIntersectionObserverRef] = useIntersectionObserverRef(callback)
    // Should only work for Button
    const newRef = useForkRef(ref, myIntersectionObserverRef)

    return <div ref={newRef}></div>
  }
)
```

**Expected behavior**
`useForkRef` should not throw error for ref being null
assignment of `ref={newRef}` should throw error because the element is not button but a div

**Screenshots**
![image](https://user-images.githubusercontent.com/754818/170154937-94faa358-b257-465b-bad1-3d245b579bf1.png)

**Comment by qqpann** [comment]
@imbhargav5 Is this closed, since it is related to a PR?
