### ISSUE TITLE
Usekeys - incorrectly triggered after multi key press.

### ISSUE THREAD

**Issue by trobe211** [imbhargav5/rooks#1018]
**Describe the bug**
If you press multiple keys to trigger an event, that same event can be triggered again by pressing the last key. E.g. Click CtrlLeft + z to trigger an event, can be triggered again by only pressing z. 

**To Reproduce**
1. Go to the codesandbox on the rooks [useKeys](https://react-hooks.org/docs/useKeys) page [here](https://codesandbox.io/s/usekeys-uzlde?from-embed)
2. Press CtrlLeft + z to trigger the event.
3. Only press z the next time and see that the event is triggered again.

**Expected behavior**
The event should only be triggered if all the specified keys are pressed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 101.0.1210.32

**Additional context**
I believe the problem arises from this code snippet in useKeys.ts
![usekeys](https://user-images.githubusercontent.com/40841776/170190368-578a1a1e-2a13-4e09-ae26-8ec1d6210e5f.PNG)
When debugging, I found that only the last pressed key was being set to false in PressedKeyMapping, so if you pressed CtrlLeft + z, only z would get set back to false, while control would remain true. So only pressing z would trigger the event as control is still set to true.

**Comment by trobe211** [comment]
I have patched this in my project and it seems to be working. I have forked the project and committed the change [here](https://github.com/trobe211/rooks/commit/ed02b1457750cc7463f54b974ecd084bb4aeac3b). With my limited exposure to the code I imagine someone may have a better solution than this. The idea was that if the keys pressed weren't continuous, set all in the PressedKeyMapping to false.

**Comment by qqpann** [comment]
It looks like this issue is caused when you call `alert`. 
Without calling alert, the current code works fine.
But when you call alert when the combination of keys is pressed, the `keyup` event is not tracked while the alert is present, causing this issue.

**Comment by qqpann** [comment]
Also, it may be worth noting that keeping pressing a normal key (such as M) and the control key has different behavior.
Keeping pressing a normal key will trigger `keydown` periodically, while keeping press control key will only trigger `keydown` once at the beginning.
