### ISSUE TITLE
New useGeolocation is stuck in an infinite loop.

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#103]
https://dev.react-hooks.org/?path=/story/usegeolocation--basic-example-geolocation-conditional

**Comment by simbathesailor** [comment]
Ohh, I will have a look in sometime.

**Comment by imbhargav5** [comment]
Let's put in a test case to make sure this is covered.

**Comment by imbhargav5** [comment]
Fixed with e5963ccca2aea6ce90b725ad2b916692cd47e60d
