### ISSUE TITLE
`useWillUnmount` is broken now

### ISSUE THREAD

**Issue by aso1datov** [imbhargav5/rooks#1109]
**Describe the bug**
After this [PR](https://github.com/imbhargav5/rooks/pull/1071) `useWillUnmount` cannon be used with anonymous function  because it is called every render. If this behavior is intended that way, then a major version should have been released because it is breaking change.

**To Reproduce**
https://codesandbox.io/s/competent-albattani-co2vte?file=/src/App.tsx

**Expected behavior**
`useWillUnmount`'s callback fired only on unmount

**Comment by imbhargav5** [comment]
👀 Yikes. This was a massive oversight. Reverting.
