### ISSUE TITLE
`useWindowSize()` Unsafe assignment of an `any` value

### ISSUE THREAD

**Issue by Talent30** [imbhargav5/rooks#1139]
**Describe the bug**
`  const { innerWidth } = useWindowSize();
`eslint return Unsafe assignment of an `any` value.
**To Reproduce**
1. Install rooks@5.11.8
2. `  const { innerWidth } = useWindowSize();`

**Expected behavior**
return a correct type

**Comment by imbhargav5** [comment]
@Talent30 I believe this has been fixed in the latest release.

**Comment by Talent30** [comment]
Hi, @imbhargav5. 

Thank you for your response.
Unfotunatily I am using the latest release of rooks which is [v5.11.8](https://github.com/imbhargav5/rooks/releases/tag/v5.11.8)
<img width="898" alt="image" src="https://user-images.githubusercontent.com/12595973/178824907-22fa6a31-30f4-418c-8ac8-f5dc2539abcc.png">

**Comment by imbhargav5** [comment]
@Talent30 I am going to reopen the issue, but would love if you can share more info on this one.

**Comment by Talent30** [comment]
@imbhargav5 Hi, thank you for your reply!

<img width="427" alt="image" src="https://user-images.githubusercontent.com/12595973/182981627-0083284b-b43a-44a5-bd10-381151062f45.png">
<img width="783" alt="image" src="https://user-images.githubusercontent.com/12595973/182981726-99c70d48-f9e1-474f-9f70-ebd8a629a500.png">
The problem seems to have been solved after a certain nextjs update
