### ISSUE TITLE
useAsyncEffect

### ISSUE THREAD

**Issue by akiszka** [imbhargav5/rooks#1142]
Hello,

I would propose to add a useAsyncEffect hook to rooks. This hook would be a simple clone of useEffect that accepts an async function.

I can write the hook and create a pr, but I would first like to know if there is demand for this kind of thing.

# Rationale

I often find myself writing lots of boilerplate code when running an async function inside useEffect. UseEffect only works with effect functions that have the type signature `() => (void | Destructor)`, so this is unacceptable:

`useEffect(async () => { ... })`

Because of this I find myself writing code similar to:

```jsx
useEffect(() => {
    (async () => {
        ...
    })()
})
``` 

which can get messy quickly, especially for short functions, or code like:

```jsx
useEffect(() => {
    doSomething()

    async function doSomething() {
        ...
    }
})
```

which looks relatively innocent, but note that the effect function now has 4 extra lines. This can quickly add up, especially when you call 3+ useEffects in a component.

All this could be replaced with a simple hook like:

```jsx
useAsyncEffect(async () => {
    ...
})
```

# Basic implementation

Below is an extremely basic implementation for context:

```tsx
import React, { useEffect } from "react";

type Effect = () => Promise<void>;
type CleanupFunction = () => void;

export function useAsyncEffect(effect: Effect, deps?: React.DependencyList, cleanup?: CleanupFunction) {
    useEffect(() => {
        effect()
        return cleanup
    }, deps)
}
```

**Comment by imbhargav5** [comment]
@akiszka Looks like a great idea! Do you have any thoughts on how to clean up pending promises if a component un-mounts before the async task has finished? I guess we can use AbortController or something. What do you think?

**Comment by imbhargav5** [comment]
@akiszka Yeah we should use AbortController. I am not sure we need cancellable option right now. We can make all of them cancellable on unmount and if there are specific repetitive edge cases we can take a call then.

**Comment by qqpann** [comment]
This looks like good to close? @imbhargav5

**Comment by imbhargav5** [comment]
Yep! I used @akiszka's code and then made some small changes and the hook is now live.

**Comment by imbhargav5** [comment]
Thanks a lot @akiszka !
