### ISSUE TITLE
Incorrect path to type definitions

### ISSUE THREAD

**Issue by patik** [imbhargav5/rooks#1148]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `rooks@5.11.8` for the project I'm working on. I got an error about the path to the type definitions being unresolvable. I'm using Yarn 1.22 with a Next.js project.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/rooks/dist/types/index.d.ts b/node_modules/rooks/dist/types/index.d.ts
index b1d9752..8cfb21d 100644
--- a/node_modules/rooks/dist/types/index.d.ts
+++ b/node_modules/rooks/dist/types/index.d.ts
@@ -1,7 +1,7 @@
 /// <reference types="react" />
 import { MutableRefObject, Dispatch, SetStateAction, LegacyRef, useEffect, Ref } from 'react';
 import { DebounceSettings, DebouncedFunc } from 'lodash';
-import { ListenerOptions, DeepNullable } from '@/types/utils';
+import { ListenerOptions, DeepNullable } from '../esm/types/utils';
 
 /**
  * useBoundingclientRect hook

**Comment by imbhargav5** [comment]
Hi @patik, interesting. I actually don't know how to fix this. Do you have a fix in mind? If yes, could you help with a PR if it's a quick one?

**Comment by imbhargav5** [comment]
@patik Is this still an issue?

**Comment by patik** [comment]
It is still an issue for me. When I use `tsc` to lint my code, I get this error:

```sh
$ tsc --jsx react-jsxdev --noEmit
../node_modules/rooks/dist/types/index.d.ts:4:47 - error TS2307: Cannot find module '@/types/utils' or its corresponding type declarations.

4 import { ListenerOptions, DeepNullable } from '@/types/utils';
                                                ~~~~~~~~~~~~~~~


Found 1 error in ../node_modules/rooks/dist/types/index.d.ts:4

error Command failed with exit code 2.
```

It looks like it's just an incorrect path to the `utils` file. But I'm not sure why no one else is having the issue. I'm using yarn 1.22.15 and TS v4.7.4.
