### ISSUE TITLE
[5.13.1] esm packaging error with @/utils/noops allias (regression from 5.12.0). 

### ISSUE THREAD

**Issue by belgattitude** [imbhargav5/rooks#1153]
**Describe the bug**

Using latest 5.13.1 (probably 5.13.0 too) broke the builds. I complains about `Module not found: Can't resolve '@/utils/noop'`

```
../../node_modules/rooks/dist/esm/hooks/useIntersectionObserverRef.js:1:0
Module not found: Can't resolve '@/utils/noop'
Import trace for requested module:
../../node_modules/rooks/dist/esm/index.js
./src/features/demo/blocks/jumbotron/Jumbotron.tsx
./src/features/demo/blocks/index.ts
./src/features/demo/pages/DemoPage.tsx
./src/features/demo/pages/index.ts
./src/pages/index.tsx
https://nextjs.org/docs/messages/module-not-found
../../node_modules/rooks/dist/esm/hooks/useInterval.js:2:0
Module not found: Can't resolve '@/utils/noop'
Import trace for requested module:
../../node_modules/rooks/dist/esm/index.js
./src/features/demo/blocks/jumbotron/Jumbotron.tsx
./src/features/demo/blocks/index.ts
./src/features/demo/pages/DemoPage.tsx
./src/features/demo/pages/index.ts
./src/pages/index.tsx
https://nextjs.org/docs/messages/module-not-found
../../node_modules/rooks/dist/esm/hooks/useIntervalWhen.js:1:0
Module not found: Can't resolve '@/utils/noop'
Import trace for requested module:
../../node_modules/rooks/dist/esm/index.js
./src/features/demo/blocks/jumbotron/Jumbotron.tsx
./src/features/demo/blocks/index.ts
./src/features/demo/pages/DemoPage.tsx
./src/features/demo/pages/index.ts
./src/pages/index.tsx
https://nextjs.org/docs/messages/module-not-found
```

**To Reproduce**

You can see the result of the CI failure

- **Nextjs**: https://github.com/belgattitude/nextjs-monorepo-example/runs/7480270401?check_suite_focus=true
- **Storybook**: https://github.com/belgattitude/nextjs-monorepo-example/runs/7480270379?check_suite_focus=true

And the upgrade PR: https://github.com/belgattitude/nextjs-monorepo-example/pull/2326

**Screenshots**

![image](https://user-images.githubusercontent.com/259798/180602232-7dd29fd4-fccd-4025-87fb-595ee29d9b41.png)

**Comment by imbhargav5** [comment]
@belgattitude Thanks for pointing this out! Will look into this one. Should find a fix by tomorrow EOD.

**Comment by imbhargav5** [comment]
A fix is in the works. https://github.com/imbhargav5/rooks/pull/1154 .

**Comment by imbhargav5** [comment]
Issue seems to have been fixed in the PR. merging. Hopefully it works for you .

**Comment by imbhargav5** [comment]
Closing this issue as I tested that 5.13.2 works. Please reopen if you still see the issue.

**Comment by belgattitude** [comment]
Great thank you very much.  Really love rooks.
