### ISSUE TITLE
useIntersection hook that tracks two refs interesection or tracks intersection with one ref and viewport

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#1177]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Chaitanya7666** [comment]
@imbhargav5 Are you looking for someone to take this up? If so, I would like to take it up with a little bit of explanation. 

FYI, I have neither created a custom hook nor know TS.

**Comment by imbhargav5** [comment]
@Chaitanya7666 Go ahead!

**Comment by Chaitanya7666** [comment]
Actually, I did not understand the use case of this hook. Could you please point me out to any resource on the internet that the `useIntersection` hook tries to simplify or explain me briefly what's expected?
