### ISSUE TITLE
Create usePerformance hook

### ISSUE THREAD

**Issue by maciekgrzybek** [imbhargav5/rooks#119]
**Is your feature request related to a problem? Please describe.**
Recently in my job, I was working on large application, and we had to change/throttle some functionalities according to the user's device CPU, memory, etc. We could build a hook that will return info about it. There's a native API - [Performance Observer](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver), similar to Mutation and Intersection Observer that we could use.

**Describe the solution you'd like**
Create a hook that will return information about the device hardware.

**Describe alternatives you've considered**
No alternatives that I'm aware of.

I'm happy to work on that.

**Comment by imbhargav5** [comment]
Hey good idea. However this use case isn't common enough to be in a generic package likes rooks IMO.

**Comment by maciekgrzybek** [comment]
Ok make sense. Closing the issue.
