### ISSUE TITLE
Update contributing.md to include changesets information

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#1194]
Reference - https://github.com/statelyai/xstate/blob/main/CONTRIBUTING.md

**Comment by Chaitanya7666** [comment]
Hey @imbhargav5 , I checked the reference document that you have added. I don't see anything related to `changsets` in that doc. However, I noticed a `.changeset` folder in the root of the project.

If you could elaborate more on the issue, I would be able to take up the issue and I would love to work on it.

**Comment by imbhargav5** [comment]
@Chaitanya7666 Of course! So we are now using changesets for releases. The commands are very similar to the reference document I linked. Every PR needs to have a changeset information linked to it if it fixes a bug/ adds a new feature or introduces a breaking changes. 

`yarn changeset add` adds a new changeset and the contributor can select which packages need to be bumped to which version. 
then it has to be committed into the PR. 

Our github CI and Semantic release action takes care of publishing the versions automatically.

**Comment by Chaitanya7666** [comment]
I partially got it. I think that it would be good to add details on `how to add changeset` under [this section](https://github.com/imbhargav5/rooks/blob/main/CONTRIBUTING.md#contributing-guidelines). What do you think? If that's good, please assign this issue to me.

**Comment by imbhargav5** [comment]
@Chaitanya7666  Yep go for it. If there are any changes I will let you know in the PR. All yours!

**Comment by Chaitanya7666** [comment]
[Link to PR](https://github.com/imbhargav5/rooks/pull/1209)
