### ISSUE TITLE
react-hooks.org returns 404

### ISSUE THREAD

**Issue by itsmingjie** [imbhargav5/rooks#1199]
Looks like something was misconfigured and the entire website is now 404'ing. 

<img width="1708" alt="404 NOT_FOUND - Google Chrome Dev - 2022-08-03 at 10 54 53@2x" src="https://user-images.githubusercontent.com/13333578/182654079-fc763b73-8117-4bac-a4c7-acf3d36e1b87.png">

**Comment by imbhargav5** [comment]
@itsmingjie Thanks for reporting this! Will look into it.

**Comment by imbhargav5** [comment]
@itsmingjie Looks like a weird error on Vercel's end. I just had to redeploy and it deployed correctly. 🤔 Looks like the site's back up! Thanks!

**Comment by itsmingjie** [comment]
Thanks for the swift response!

**Comment by imbhargav5** [comment]
Just a heads up. This issue seems intermittent. I will probably have keep an eye on this one until Vercel releases Turborepo related advancements as publicized on their twitter handle in the next couple of weeks.

**Comment by qqpann** [comment]
@imbhargav5 It seems to be down again.

**Comment by imbhargav5** [comment]
@qqpann unfortunately this keeps happening only in vercel. I think turborepo build is somewhat broken in vercel.

**Comment by qqpann** [comment]
@imbhargav5 That's unfortunate. Did you try to redeploy without cache on vercel?

**Comment by imbhargav5** [comment]
@qqpann I just keep doing that every time it fails and then it works until the next deploy.

**Comment by qqpann** [comment]
<img width="942" alt="スクリーンショット 2022-08-07 15 44 46" src="https://user-images.githubusercontent.com/17402261/183278761-d79f3a11-7cab-43b3-9c9e-99fbc0b3598f.png">
@imbhargav5  Did you configure the root directory?

**Comment by imbhargav5** [comment]
@qqpann Yeah I did. That's why it works when I redeploy. It only doesn't work the first time it runs.
