### ISSUE TITLE
The hook names surrounded by `` in the markdown disappears in the new website UI

### ISSUE THREAD

**Issue by qqpann** [imbhargav5/rooks#1208]
For example in useKeys, the hook names disappears.

Markdown:
```md
An important difference between `useKey` and `useKeys` is that `useKey` checks if **EITHER** of the keys in the list is pressed, while `useKeys` checks if **ALL** of the keys in the list are active.
```

UI:
<img width="815" alt="スクリーンショット 2022-08-04 16 44 41" src="https://user-images.githubusercontent.com/17402261/182792579-21f7955e-3e72-4351-afde-9d84f66275dc.png">

**Comment by imbhargav5** [comment]
Ahh. hmmm. I think we need to change the logic for `code` blocks where we are rendering sandpack.

**Comment by imbhargav5** [comment]
https://github.com/imbhargav5/rooks/blob/main/apps/website/src/components/MDXRenderer/components.tsx#L131 Some change needs to occur here.

**Comment by qqpann** [comment]
I looked at it, a quick fix seems to just remove `code: Code`.

@imbhargav5 I'm not familiar with mdx, do you have some reference to the components available?

**Comment by imbhargav5** [comment]
@qqpann Ah so I think I only wrote a couple of components, I one mainly for `pre:` which will spawn up a sandpack, but if removing `code:Code` will solve the problem and nothing else breaks, we can go with it for sure.
