### ISSUE TITLE
Some hooks in the sidebar leads to 404 page

### ISSUE THREAD

**Issue by qqpann** [imbhargav5/rooks#1218]
These hooks in the sidebar leads to 404 page:
- useVisibilitySensor
- useSuspenseResource

Maybe the hooks is already removed?

**Comment by imbhargav5** [comment]
Ah this is correct. useVisibilitySensor is removed and useSuspenseResource idea was discarded. I will remove them. THanks @qqpann !

**Comment by imbhargav5** [comment]
Should be fixed now.

**Comment by qqpann** [comment]
Confirmed, locally.
