### ISSUE TITLE
Looking for contributors to build out the new website

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#1222]
We are currently in the process of redesigning the entire rooks website and add better documentation. The design is expected to be finished by Aug 31st and we are looking for contributors to help build out the website in September. 

Let us know if you are interested!

**Comment by hokagedemehin** [comment]
We can we see more details on the tools, libraries, frameworks etc that you plan to use to build the new website

**Comment by Chaitanya7666** [comment]
Hey @imbhargav5 , I would be interested to contribute to the website. Please take me into account.

**Comment by imbhargav5** [comment]
@hokagedemehin @Chaitanya7666 The website tech is as follows - Next.js, Radix UI, Stitches. And the code is at apps/website in the repo. 

Once the design is completed, I will split the work into small tasks and tag you and you can take up the ones which interest you. Thanks!

**Comment by Chaitanya7666** [comment]
@imbhargav5 , Does the design have a link that you could share? If so, could you please share it because I would like to check it out frequently? I just want to be able to see how the design evolves over time during this month.

**Comment by hokagedemehin** [comment]
A nice choice for the framework and libraries. The new website will be blazing fast. Although I have not used Radix for any of my past projects, I believe my experience with other UI libraries like Material UI, Chakra UI & Bootsrap should help

**Comment by qqpann** [comment]
Radix UI & Stitches sounds pretty modern and fun! Please count me in as well 😃

**Comment by dhavalwd** [comment]
Hey @imbhargav5 I am interested to contribute to the new website. Let me know how I can help.

**Comment by Chaitanya7666** [comment]
> We are currently in the process of redesigning the entire rooks website and add better documentation. The design is expected to be finished by Aug 31st and we are looking for contributors to help build out the website in September.
> 
> Let us know if you are interested!

Hey @imbhargav5 , do you have any updates on when we are getting started?

**Comment by imbhargav5** [comment]
We will be using https://ui.shadcn.com/

**Comment by 7777chaitanya** [comment]
When are we getting started, @imbhargav5 ? Do we have any designs for the new website?
