### ISSUE TITLE
Documentation Website Keeps Crashing

### ISSUE THREAD

**Issue by hokagedemehin** [imbhargav5/rooks#1248]
Hi @imbhargav5,

Please is there any reason why the website keeps showing me a 404 every time? It was working before but now it shows me 404 pages on any link I go to.

Kindly assist

**Comment by imbhargav5** [comment]
@hokagedemehin I am in touch with the Vercel support to figure out why. Not much on our end but figuring out with the support staff.

**Comment by imbhargav5** [comment]
This seems to have been fixed. Haven't seen this happen in the last 3-4 days but let's open if this repeats.
