### ISSUE TITLE
Let's add exhaustive-deps lint rule, for better hooks development 

### ISSUE THREAD

**Issue by simbathesailor** [imbhargav5/rooks#129]
**Is your feature request related to a problem? Please describe.**
A lint rule, which prevents doing mistakes while writing hooks in this repository.

**Describe the solution you'd like**
Add  exhaustive-deps rule and respective npm package is https://www.npmjs.com/package/eslint-plugin-react-hooks#installation

**Comment by maciekgrzybek** [comment]
Can I add that?

**Comment by simbathesailor** [comment]
Hi @maciekgrzybek : Thanks a lot. One pull request is already there for exhaustive deps , https://github.com/imbhargav5/rooks/pull/134.  Although the pr has other fixes as well, You can review the eslint plugin part it and let me know if anything is missing

**Comment by maciekgrzybek** [comment]
Hi @simbathesailor , just checked that, look fine in my opinion :)
