### ISSUE TITLE
useOnline should have correct initial state

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#132]
useOnline currently default starts to false. Let's set it `navigator.onLine` in browser env and `true` in server env.

**Comment by simbathesailor** [comment]
Hi @imbhargav5 ,
If we are adding true as default state for online in nodejs, won't that be wrong ? Should we log some warning message in case if the user is using in nodejs environment. 
As far as i understand , the network online status at server level depends, the serve might be able to reach some other servers, but not other servers. There is no browser there.

**Comment by imbhargav5** [comment]
Actually you are right. We should initialize it to `true` and put in a warning. Technically the fact that  a request went to the server means that the user is `online` right?

**Comment by simbathesailor** [comment]
Hi @imbhargav5 ,
I mean I think the useOnline will be used in some components(function), so the function can be run at either client side or server side (in case of server side rendered app). In server side case, what should be the criteria to say that it is online, because  we don't need  internet to connect to local server which is responsible for creating html and sending it to client. In that case defaulting to true will be right thing ?

**Comment by imbhargav5** [comment]
We can actually make it return null on server side too.

**Comment by maciekgrzybek** [comment]
What's the decision on this one? I could work on it if needed

**Comment by imbhargav5** [comment]
Yes please. So on the server, let's keep it simple and return `null` on the server side and on the client side we should initialize it with the online status during init. @maciekgrzybek

**Comment by maciekgrzybek** [comment]
Hey guys, just did a PR, not sure if that's what you wanted - https://github.com/imbhargav5/rooks/pull/140

**Comment by thibaultboursier** [comment]
Hello @simbathesailor @imbhargav5 

Beyond the environment problem, I think it's not a good thing to set "false" state value by default, and then, inside effect (the second, in the order), set good state value (the result of getIsOnline function call). 

We could use a callback function inside useState, and return result of getIsOnline method inside. It will also avoid to have a bad transition between original "false" value and new value setted in the effect, as the effect will run after the render is committed to the screen.

`
function useOnline() {
  const [online, changeOnline] = react.useState(() => getIsOnline());
 ...     
}
`

What is your opinion ?

**Comment by imbhargav5** [comment]
Agreed.

**Comment by maciekgrzybek** [comment]
I think that can be closed now right?
