### ISSUE TITLE
No example for useAsyncEffect

### ISSUE THREAD

**Issue by ddsuhaimi** [imbhargav5/rooks#1321]
Currently, no example is found for [useAsyncEffect()](https://github.com/imbhargav5/rooks/blob/main/data/docs/useAsyncEffect.md?plain=1#L16)

Check out [the docs](https://react-hooks.org/docs/useAsyncEffect)

**Comment by imbhargav5** [comment]
@ddsuhaimi Ah that's true. Would you like to try adding an example in a PR? Would appreciate it very much!

**Comment by ddsuhaimi** [comment]
> @ddsuhaimi Ah that's true. Would you like to try adding an example in a PR? Would appreciate it very much!

I am not sure how useAsyncEffect works to be honest, do I just copy this [example](https://github.com/imbhargav5/rooks/blob/main/packages/rooks/src/hooks/useAsyncEffect.ts#L17-L30)?

**Comment by imbhargav5** [comment]
@ddsuhaimi There is also an example in the test case here.  https://github.com/imbhargav5/rooks/blob/main/packages/rooks/src/__tests__/useAsyncEffect.spec.ts#L175 

As long as it covers at least the ones in the test cases, the PR will be super 🔥
