### ISSUE TITLE
[V7] Bundled umd does not pass es2015-es2019 checks

### ISSUE THREAD

**Issue by belgattitude** [imbhargav5/rooks#1362]
The bundled `dist/umd/rooks.umd.js` contains an [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) which is probably too modern for some browsers. 

- see support https://caniuse.com/mdn-javascript_operators_optional_chaining

Not sure if it's intended as it does not appear in esm and cjs bundles. If it is would be interesting to mention it in the changelog and align the bundles.

![image](https://user-images.githubusercontent.com/259798/187943420-28480a47-1dc3-45c6-a137-15200b33ffba.png)

## Info

- PR: https://github.com/belgattitude/nextjs-monorepo-example/pull/2551
- Failing test: https://github.com/belgattitude/nextjs-monorepo-example/runs/8135920555?check_suite_focus=true

## To reproduce

clone the `renovate/rooks-7.x` branch from https://github.com/belgattitude/nextjs-monorepo-example

```bash
yarn install
cd apps/nextjs-app
yarn build && yarn check-dist
// or
yarn es-check es2016 "../../node_modules/rooks/dist/umd/**.js"
```

**Comment by imbhargav5** [comment]
@belgattitude Thanks for this! Do you happen to know a solution to fix this easily? If you can submit a PR or guide us to a solution we can fix this quickly. Appreciate it! 🚀

**Comment by belgattitude** [comment]
Sure I'll have a look this week-end.

**Comment by belgattitude** [comment]
Hey @imbhargav5 now that I opened the repo, I see multiple things that would make sense to fix.

First I'd like to rework the exports field (would love to remove unpkg field too - that's the reason why nextjs picked up the umd build, rather than cjs or esm)

Second I feel for bundling esm/cjs I'd like to go with tsup if it makes sense to you. 

Third I'm wondering if I could remove the bundled test files.

I'll plan to make some PR's whenever I have time so you can follow and give me directions if needed.

Enjoy your day

**Comment by imbhargav5** [comment]
@belgattitude Wow. Please go ahead and make a PR. I am not entirely sure of all the changes but it seems like you have a solid idea of the ideal setup. Once you make a PR based on your idea, I will do a thorough review and get it shipped asap.
