### ISSUE TITLE
Problem with inferring type in useDebounce

### ISSUE THREAD

**Issue by aso1datov** [imbhargav5/rooks#1411]
**Problem:**
When using the `useDebounce` hook, typescript warns about an argument type mismatch. It starts since version 6.

<img width="642" alt="Screenshot 2022-09-12 at 15 06 16" src="https://user-images.githubusercontent.com/8918168/189638534-dc60fb30-6391-479e-8f48-7901181caa4b.png">

**Example:** 
https://codesandbox.io/s/sweet-dijkstra-sm3ju2?file=/src/App.tsx

**Comment by imbhargav5** [comment]
@aso1datov Thanks for submitting this issue! I will take a look at this one.

**Comment by imbhargav5** [comment]
Should be fixed now.
