### ISSUE TITLE
create useFullscreen?

### ISSUE THREAD

**Issue by braxtonchristensen** [imbhargav5/rooks#144]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
I'm always frustrated when I am trying to make an app fullscreen, making it compatible for all browsers, remembering each API.

**Describe the solution you'd like**
a `useFullscreen` hook that will return a fullscreen toggle event that could be attached to an onClick handler to toggle fullscreen.

**Describe alternatives you've considered**
a non react specific library could be used. 

**Additional context**

**Comment by simbathesailor** [comment]
@braxtonchristensen, Thanks for raising this feature request. I found this article, which might be useful.  https://hacks.mozilla.org/2012/01/using-the-fullscreen-api-in-web-browsers/

**Comment by imbhargav5** [comment]
Yes please! Feel free to send in a PR!
