### ISSUE TITLE
create useClipboard?

### ISSUE THREAD

**Issue by braxtonchristensen** [imbhargav5/rooks#145]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. I'm always frustrated when trying to use the clipboard api for different browsers.

**Describe the solution you'd like**
a useClipboard hook that would return whatever is currently on your clipboard as well as a function that would set the clipboard with whatever argument is given.

**Describe alternatives you've considered**

**Additional context**

**Comment by imbhargav5** [comment]
Yes please!

**Comment by maciekgrzybek** [comment]
I can take a look

**Comment by braxtonchristensen** [comment]
I have a PR I am cooking up @maciekgrzybek
