### ISSUE TITLE
useLocalstorage - lowercase s

### ISSUE THREAD

**Issue by lookfirst** [imbhargav5/rooks#148]
https://github.com/imbhargav5/rooks/blob/dev/packages/localstorage/src/useLocalstorage.ts#L23

Why is it exported to the public as useLocalstorage when the function is useLocalStorage?

**Comment by imbhargav5** [comment]
Ah so the template to creating hooks has a pattern. A hook exported within `localstorage` becomes `useLocalstorage` and if it is exported in `local-storage` it becomes `useLocalStorage`. Here it should be `useLocalstorage` and it is a typo.

**Comment by harshzalavadiya** [comment]
@imbhargav5 do we want to correct typo?
If so I can work on this issue and submit PR

**Comment by imbhargav5** [comment]
@harshzalavadiya Yes definitely! Thanks!

**Comment by lookfirst** [comment]
soo.... can you fix it?

**Comment by lookfirst** [comment]
Oh shoot... wait a second... I was thinking you'd fix it to be the right camel case... useLocalStorage!

**Comment by harshzalavadiya** [comment]
@lookfirst, if we do `useLocalStorage` that means published npm package `use-localstorage` has to be deprecated and replaced with `use-local-storage` that might prevent so many users from upgrading to newer version.
so sticking with the package named seemed like a good idea

**Comment by lookfirst** [comment]
The name of the variable in the browser is `localStorage` not `localstorage`. 🤷‍♂ you made a mistake, seems like perpetuating it is a bummer.

**Comment by harshzalavadiya** [comment]
@lookfirst, Yes, I agree that's an mistake. but I was thinking about not abandoning many people
@imbhargav5, If everyone agrees then I'm happy to submit new PR for `use-local-storage` and `use-session-storage` and deprecating `use-localstorage` and `use-sessionstorage`

**Comment by lookfirst** [comment]
abandoning people? it is a 1 character change.

**Comment by harshzalavadiya** [comment]
renaming NPM package means deprecating `use-localstorage` and using `use-local-storage` entire new package existing users that use `use-localstorage` won't be able to receive updates.

one workaround might be using same package and exporting member as `useLocalStorage` that might be middle ground as of now. If that's possible I'll submit PR for that today

**Comment by imbhargav5** [comment]
Let's not go for `use-local-storage` right now.

**Comment by harshzalavadiya** [comment]
Then current open PR will settle it as middle ground
