### ISSUE TITLE
useSelectableList does not support object list

### ISSUE THREAD

**Issue by dohomi** [imbhargav5/rooks#1496]
There is a bug in useSelectableList, currently only number/string are supported as object list.

https://github.com/imbhargav5/rooks/blob/main/packages/rooks/src/hooks/useSelectableList.ts#L60

it could be fixed with `find` but its unknown which identifier is the `value`.

**Comment by dohomi** [comment]
Well it seems to work, but quite frickle. Seems to be necessary to use `useMemo` on option level otherwise it looses the reference on items

**Comment by imbhargav5** [comment]
Hi @dohomi Thanks for taking this up! I will take a look at this tomorrow!
