### ISSUE TITLE
useInput - How to clear input value ?

### ISSUE THREAD

**Issue by oldmember** [imbhargav5/rooks#151]
Hello,
I use your hook to make a to do list. Every time I create new todo by pressing enter, the old input value is still in Input element. How to clear it like setState("") ?

**Comment by imbhargav5** [comment]
@oldmember There are a couple of ways of doing it depending on how you are using the input. Do you have an example snippet by any chance? One way is to call `onChange({ target : { value : ""}})`. Another cleaner way is to simply use the `key` prop to reinit the component that is using the hook.
