### ISSUE TITLE
fix: useKeys never trigger in cypress 

### ISSUE THREAD

**Issue by NsdHSO** [imbhargav5/rooks#1565]
Hi, I use useKeys to make a shortcut to find something in apps, when I wanted to test the app e2e with Cypress combination cmd+k never has been triggered. Please if someone can help me, Tnx.
![image](https://user-images.githubusercontent.com/37635083/205227538-b7081d74-955d-479a-b0d2-5641043cd9c2.png)

**Comment by imbhargav5** [comment]
Hmm, I not sure why that is but perhaps you can try using the original `useKey` or `useKeyRef` hook for your usecase and see if you can side step the issue? suggesting mainly because debugging Cypress can be a bit difficult for us.

**Comment by NsdHSO** [comment]
Solution: 
`
**cy.wait(500);**

cy.get('body').type('{meta}k')
....
`
