### ISSUE TITLE
[BUG] useLocalstorageState cast undefined to "undefined"

### ISSUE THREAD

**Issue by nghiepdev** [imbhargav5/rooks#1566]
From the 2nd time `useLocalstorageState` force `undefined` into `"undefined"`

https://user-images.githubusercontent.com/4768095/209631470-22834cde-60a9-4e43-b3eb-144d9acc7d7a.mov

**Comment by johndatserakis** [comment]
I'm getting this as well.

```tsx
const [cookie, setCookie] = useLocalstorageState<CookieValue | undefined>(COOKIE_NAME, undefined);
```

<img width="458" alt="Screen Shot 2023-03-25 at 11 10 30 PM" src="https://user-images.githubusercontent.com/9972969/227753115-e8ca2af3-36b7-4dd4-9ae2-bbd28b73034c.png">.
