### ISSUE TITLE
New hook idea - useSwipe

### ISSUE THREAD

**Issue by maciekgrzybek** [imbhargav5/rooks#157]
I think it would be a good idea to create useSwipe hook, to detect swiping on touch devices. We could use [Hammer.js](https://hammerjs.github.io/) library as it's battle tested, well documented and maintained.

What do you think?

**Comment by imbhargav5** [comment]
Yeah definitely. Now that this project https://github.com/JedWatson/react-hammerjs isn't as active it's definitely a good idea. However that would mean addding Hammer.js to the `rooks` project which will a) create a dependency chain b) Increase bundle size.

This should be a separate package like JedWatson created.
