### ISSUE TITLE
the returned set action from useLocalStorageState does not fully satisfy the Dispatch<SetStateAction<T>> signature

### ISSUE THREAD

**Issue by airtonix** [imbhargav5/rooks#1572]
The type for `SetStateAction<T>` is : 

```ts
    type SetStateAction<S> = S | ((prevState: S) => S);
```

Where as the `set` function in `useLocalStorageState` ends up assuming that the value will not be a function: 

-  [here it works as expected](https://github.com/imbhargav5/rooks/blob/main/packages/rooks/src/hooks/useLocalstorageState.ts#L175) 
- [The deviation begins here](https://github.com/imbhargav5/rooks/blob/main/packages/rooks/src/hooks/useLocalstorageState.ts#L176), where it should test if `value` is a function and run it while providing the state to the function then pass that on to the `broadcastValueWithinDocument`.

So if I use this like : 

```ts

const [value,setValue,removeValue] = useLocalStorageState('someKey', {})

useEffect(() => {
  setValue((current) => ({...current, lol: 'nope'}) )
  assert(localStorage.getItem('someKey') === 'undefined')
},[]);


```

**Comment by airtonix** [comment]
Imagine my surprise when all my valid use of `setState` from this  hook mysteriously resulted in my localstorage value ending up as `undefined` : 
![image](https://user-images.githubusercontent.com/61225/217719269-579f153b-000a-4dcd-bae8-85a5e4e5d3fc.png)

**Comment by imbhargav5** [comment]
@airtonix That is true. This is a bug. Please consider creating a PR if you would like to fix this issue, else I will get to it. 😄

**Comment by imbhargav5** [comment]
@airtonix I have fixed this in a local PR. Will publish this week.

**Comment by imbhargav5** [comment]
@airtonix Please check the latest release of rooks. I think it will suffice.
