### ISSUE TITLE
types for useDebouncedValue

### ISSUE THREAD

**Issue by TkDodo** [imbhargav5/rooks#1573]
I've spotted that the types for `useDebouncedValue` are not ideal, as they alway return a union with `null`, even if we don't add the `initializeWithNull` option. Consider:

```
const [debouncedValue] = useDebouncedValue('string', 200)
```

`debouncedValue` will be of type `string | null`, even though it should be `string`

[TypeScript playground reproduction](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwK4GcCmARNAjCSB2AxmgCYBqAhgDZJoC+cAZlBCHAOQsQDWK7AsACghhCPhTwA2iRx4ipSjTQBdOAF44qTLILFy1WgAp2EqMHwBzdgBo4AJgAMDgJRCA9G7hevAPQD8QA)

the `| null` should only be added if we explicitly provide option `initializeWithNull: true`:

```
const [debouncedValue] = useDebouncedValue('string', 200, { initializeWithNull: true })
```

I think this can be solved with conditional return types and another generic. Happy to contribute this :)

**Comment by imbhargav5** [comment]
@TkDodo Thanks for pointing this out! Please feel free to submit a PR. I appreciate it!
