### ISSUE TITLE
stale closure problem with useDebounce

### ISSUE THREAD

**Issue by TkDodo** [imbhargav5/rooks#1575]
I ran into an issue today with `useDebounce`. The scenario is the following:

- we debounce an inline function
- that function closures over a value from the component
- after the function has been debounced, the value it closes over changes
--> when the debounced function runs, it still "sees" the old value from the time it was created, not the latest value.

I have a failing test-case reproduction:

```
it("should not have stale closure problems", async () => {
  const fn = jest.fn();

  function App() {
    const [value, setValue] = useState(0);
    const [done, setDone] = useState(false);

    function doSomething() {
      fn(value);
      setDone(true);
    }

    const debounced = useDebounce(doSomething, 64);

    return (
      <div>
        <button
          onClick={() => {
            debounced();
            setValue(100);
          }}
        >
          inc
        </button>
        <h1>value: {String(value)}</h1>
        <h2>done: {String(done)}</h2>
      </div>
    );
  }

  const rendered = render(<App />);
  await waitFor(() => rendered.getByText("value: 0"));
  act(() => {
    fireEvent.click(rendered.getByRole("button", { name: /inc/i }));
  });
  await waitFor(() => rendered.getByText("value: 100"));
  await waitFor(() => rendered.getByText("done: true"));

  expect(fn).toHaveBeenCalledTimes(1);
  expect(fn).toHaveBeenCalledWith(100);
});
```

what the test does is pretty similar to what happens in our app:

- we have a value set to 0
- on button click, we trigger the debounced function and immediately set the value to 100
- when the debounced function runs, it should see that the value is 100, but it still sees 0:

```
Error: expect(jest.fn()).toHaveBeenCalledWith(...expected)

Expected: 100
Received: 0
```

**Comment by TkDodo** [comment]
The only workaround in user-land I could find was to store the function on a ref so that we always get the latest value:

```
function doSomething() {
  fn(value);
  setDone(true);
}

const doSomethingRef = React.useRef(doSomething);

React.useEffect(() => {
  doSomethingRef.current = doSomething;
});

const debounced = useDebounce(() => doSomethingRef.current(), 64);
```

maybe this is something we could do inside the lib instead?

**Comment by imbhargav5** [comment]
Hmmm, I am confused. 

```
fn(value) // when this is called, isn't the value still 0?
```

**Comment by TkDodo** [comment]
No, fn(value) is part of the debounced function doSomething. When it runs, the component has already re-rendered and the value in the closure should be 100. You can see that by applying the lastet ref pattern workaround from my above comment.

**Comment by imbhargav5** [comment]
@TkDodo Ah got it. What about using `useFreshRef` here?

**Comment by TkDodo** [comment]
> What about using useFreshRef here?

oh yeah I didn't know there was a built-in hook for this 👍 . But do you agree that this is something that `useDebounce` should do internally? If so, I could contribute it.

**Comment by TkDodo** [comment]
another thing I noticed (sorry for mangling issues here, I can create a separate one if you want): If we trigger a debounced callback and the component unmounts, I would have expected the debounced callback to automatically cancel. This doesn't seem to happen. Let me know if you would think about either adding this per default or via an option, or not at all :)

Here's a test case that I would expect to pass, but it fails:

```
it("should cancel on unmount", async () => {
  const fn = jest.fn();

  function Child() {
    const debounced = useDebounce(fn, 64);

    return (
      <div>
        <button
          onClick={() => {
            debounced();
          }}
        >
          debounce
        </button>
      </div>
    );
  }

  function App() {
    const [mounted, setMounted] = useState(true);

    return (
      <div>
        <button
          onClick={() => {
            setMounted(false);
          }}
        >
          unmount
        </button>
        {mounted && <Child />}
      </div>
    );
  }

  const rendered = render(<App />);
  act(() => {
    fireEvent.click(rendered.getByRole("button", { name: /debounce/i }));
  });
  act(() => {
    fireEvent.click(rendered.getByRole("button", { name: /unmount/i }));
  });
  await wait(100);

  expect(fn).not.toHaveBeenCalled();
});
```

**Comment by imbhargav5** [comment]
@TkDodo Thanks for taking a close look at useDebounce!. So...

 > oh yeah I didn't know there was a built-in hook for this 👍 . But do you agree that this is something that useDebounce should do internally? If so, I could contribute it.

Yep I do. I do however want to make sure that we don't try to overdo it for any specific scenario and solve the problem at as much of a high level as possible (since we know that a solution to this exists on the user's end anyway). You clearly have a solution to this bug and the unmounting bug in mind and I would love it for you to submit a PR solving both. You can do them in the same issue. 

Also please make sure to submit a changeset (contributing.md shows how to do it). We also couldn't release your bug fix yesterday because of the missing changeset. 😄 I also missed that in the review. Anyway, we will release both at the same time. 

Cheers!

**Comment by TkDodo** [comment]
so I found some more issues today, like debouncing an inline function would trigger the debounce multiple times, as if it wouldn't be cancelled properly. Basically, this would log multiple times if the component re-renders in between for different reasons:

```
useDebounce(() => console.log('foo'), 2000))
```

I've reproduced this in a codesandbox here:
- https://codesandbox.io/s/boring-minsky-ymjj0f?file=/src/App.js

click the button 3 times, you'll see 3 logs. This seems to happen because the component re-renders in between. If you comment out the `setState`, you can click the button as often as you want and will only see one log, which is what I'd expect.

Not sure how this can be. For now, I have to say that we switched to a different lib, `useDebouncedCallback` from `use-debounce`. I would like to get to the bottom of it, but I'm not sure when I find the time for it, sorry.

**Comment by imbhargav5** [comment]
@TkDodo Ah I see. Thanks for helping reproduce this anyway. We will fix this when we get some time. I appreciate it. Good luck!

**Comment by imbhargav5** [comment]
cc @TkDodo Just fixed the 3 bugs you mentioned here in this PR - https://github.com/imbhargav5/rooks/pull/1576 

Please take a look when you have some time. Appreciate it 🙏

**Comment by imbhargav5** [comment]
#1576

**Comment by imbhargav5** [comment]
@TkDodo Here is a codesandbox fork of your bug reproduction where we can see the intended behaviour. https://codesandbox.io/s/funny-booth-ceb9f3?file=/src/App.js. Once again, thanks a lot for helping me improve rooks. Your tests and codesandbox reproductions helped me greatly.
