### ISSUE TITLE
`useDebouncedValue` is not installable as a standalone package

### ISSUE THREAD

**Issue by moxxuk** [imbhargav5/rooks#1582]
Running `npm i @rooks/use-debounced-value` gives me:

```
$ npm i @rooks/use-debounced-value
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@rooks%2fuse-debounced-value - Not found
npm ERR! 404
npm ERR! 404  '@rooks/use-debounced-value@*' is not in this registry.
npm ERR! 404
```

I've installed other hooks individually without issue, but `useDebouncedValue` can't be found in the registry.

**Comment by imbhargav5** [comment]
Hi @moxxuk We moved away from standalone packages in v4 because as build systems became more powerful we didn't need separate packages with treeshaking becoming more standard. 

Please install `rooks` and use any hook you like, only those hooks will be included in your main app bundle.

**Comment by moxxuk** [comment]
Hi @imbhargav5 , thanks for getting back so quickly.

That makes sense. As I'm using NextJS though, I'm using [@next/bundle-analyzer](https://github.com/vercel/next.js/tree/canary/packages/next-bundle-analyzer) for my dev environment. I can confirm this is not an issue with production builds due to tree shaking, but I am seeing all hooks included in my dev bundle with the bundle analyzer, and loading these is slowing down the dev experience (only slightly, but still...)

Any thoughts?

**Comment by imbhargav5** [comment]
Ah. I have never used this bundle analyzer before and also I don't know if treeshaking not working properly in dev, is something fixable on my end. Would you happen to know a fix? 🤔

**Comment by imbhargav5** [comment]
> Ah. I have never used this bundle analyzer before and also I don't know if treeshaking not working properly in dev, is something fixable on my end. Would you happen to know a fix? 🤔
@moxxuk

**Comment by moxxuk** [comment]
I've not tried to implement a fix yet, however I did come across this, I don't know if it's of any use but it seems related:
[Disabled SWC as replacement for Babel because of custom Babel config](https://github.com/vercel/next.js/discussions/42343)

The only thing is, I'm not using SWC, this shows up when starting the dev server:
```
info - Disabled SWC as replacement for Babel because of custom Babel config
```

**Comment by imbhargav5** [comment]
@moxxuk So is this probably any babel config on your end? Or is it in rooks? Because we only use babel with rollup to bundle and not much else.

**Comment by imbhargav5** [comment]
Closing this for now as there is no clear action. But feel free to reopen. :)
