### ISSUE TITLE
typescript error with useToggle

### ISSUE THREAD

**Issue by babycourageous** [imbhargav5/rooks#1589]
Hi there! 

When using `useToggle` in a typescript app, typescript complains that the toggle function expects an argument. 

![image](https://user-images.githubusercontent.com/14936212/226197218-18ddc4e1-b412-477e-8f0d-34f3062594b4.png)

I wasn't sure if this was intentional and just undocumented, but I was thinking that the intent is to just call the toggle function w/o parameters. 

Thanks!

**Comment by imbhargav5** [comment]
hi @babycourageous This is a definite bug. Looking into it now.

**Comment by babycourageous** [comment]
Thanks for the speedy reply!

**Comment by imbhargav5** [comment]
@babycourageous I just released this. Hopefully it fixes things. https://github.com/imbhargav5/rooks/releases/tag/rooks%407.8.1

**Comment by babycourageous** [comment]
Thanks for the very quick turnaround on that fix! I updated my package and it indeed did the trick!

**Comment by RIP21** [comment]
In version 9.5.0 it returned. Also same problem in the version 8. Version 7 is OK.

<img width="1466" height="1130" alt="Image" src="https://github.com/user-attachments/assets/1ed23f7c-647f-4f1d-b980-f279e6d188b5" />

**Comment by imbhargav5** [comment]
Ah apologies. Could you submit a pr? Having a small emergency here. I can also get to it later this week.

**Comment by RIP21** [comment]
> Ah apologies. Could you submit a pr? Having a small emergency here. I can also get to it later this week.

Submitted using GH UI, if it compiles, it will likely work :D


Tested by copy pasting to my own codebase. Works like a charm. Other cases as well.
