### ISSUE TITLE
[BUG] Could not find dependency: 'lodash' relative to '/node_modules/rooks/dist/cjs/hooks/useOnClickRef.js'

### ISSUE THREAD

**Issue by nghiepdev** [imbhargav5/rooks#1602]
Hi,
Currency `rooks` depends on `lodash` by `useOnClickRef`
```js
import { noop } from "lodash";
```
Perhaps this dependency issue exists elsewhere.
Reproduction https://codesandbox.io/s/vigilant-water-2ubyn9?file=/src/App.js
Like `lodash.debounce`, we can independently use `lodash.noop` instead.

**Comment by imbhargav5** [comment]
@nghiepdev This is a bug. On it. Thanks for pointing this out!

**Comment by imbhargav5** [comment]
@nghiepdev Fixed in 7.8.3 https://codesandbox.io/s/cool-solomon-4zmk60?file=/src/App.js:0-284 

Thanks a lot!
