### ISSUE TITLE
`useTimeout` documentation is missing returned object key `isActive`

### ISSUE THREAD

**Issue by mscottmoore** [imbhargav5/rooks#165]
**Describe the bug**
The documentation for `useTimeout` is missing documentation for the returned object key `isActive`. It only documents the returned object keys `clear` and `start`

**To Reproduce**
Go to https://react-hooks.org/?path=/story/usetimeout--basic-example and open the "Docs" tab.

**Expected behavior**
The returned object keys table should have a row documenting `isActive`

**Comment by imbhargav5** [comment]
Ah you are right. Would you like to submit a PR? 🙂
