### ISSUE TITLE
useEffectOnceWhen function declaration

### ISSUE THREAD

**Issue by ftreedom** [imbhargav5/rooks#1727]
Hi everyone,

I've encountered a strange behavior with useEffectOnceWhen today with a component like this:

```typescript
const ExampleComponent = ({condition}: {condition?: boolean}) => {

.....

useEffectOnceWhen(() => {
    // do stuff
 }, condition)

.....
}
``` 
The condition was fired every time despite the fact that the component was rendered like this: `<ExampleComponent />`
After some debugging and taking a closer look at the code I've noticed that `condition` prop is optional, and the current type declaration on `useEffectOnceWhen` is not really helpful in this case.

This is the current type definition of useEffectOnceWhen:
`declare function useEffectOnceWhen(callback: () => void, when?: boolean): void;`

I would suggest changing it like this:
`declare function useEffectOnceWhen(callback: () => void): void`
`declare function useEffectOnceWhen(callback: () => void, when: boolean): void`

This could be helpful to ensure that if a condition is passed, its value would be boolean.

I wanted to be sure that this could be an improvement for you all before opening a PR.

**Comment by mrclay** [comment]
Can you explain why passing an undefined variable to the hook is problematic? I think it’s idiomatic that functions should treat foo() and foo(undefinedVar) the same and this should be allowed by the type.
