### ISSUE TITLE
useLocalstorageState hook stores strings with extra double quotes

### ISSUE THREAD

**Issue by tayurus** [imbhargav5/rooks#1728]
I have created codesandbox playground for this issue
https://codesandbox.io/s/cold-sun-tm82rc?file=/App.js:0-674

You can check console of the playground 
![image](https://github.com/imbhargav5/rooks/assets/15295424/21f269f9-8f84-45c5-8ea2-ad29414f0e1e)

**Comment by joeljtomy** [comment]
you have to parse the value recieved from localStorage using JSON.parse function 
eg:  `console.log(
      "my-app:count with localStorage.getItem = ",
      JSON.parse(localStorage.getItem("my-app:count"))
    );`

> I have created codesandbox playground for this issue https://codesandbox.io/s/cold-sun-tm82rc?file=/App.js:0-674
> 
> You can check console of the playground ![image](https://user-images.githubusercontent.com/15295424/258367519-21f269f9-8f84-45c5-8ea2-ad29414f0e1e.png)

**Comment by tayurus** [comment]
> values are stored as strings in localStorage you have to parse the value recieved from localStorage using JSON.parse function eg: `console.log( "my-app:count with localStorage.getItem = ", JSON.parse(localStorage.getItem("my-app:count")) );`
> 
> > I have created codesandbox playground for this issue https://codesandbox.io/s/cold-sun-tm82rc?file=/App.js:0-674

It seems not obvious. At least it needs to be described in docs - https://rooks.vercel.app/docs/useLocalstorageState

**Comment by joeljtomy** [comment]
there is no need for directly taking the data from local Storage. useLocalstorageState hook  will do the parsing for you automatically if you are using the state given by the hook the whole point of the hook is to use the state and and reduce your work. even though if you have an exeptional case  you can still get the data by using JSON parsing that is the normal behaviour for localStorage access

**Comment by joeljtomy** [comment]
A similar issue was raised in  https://github.com/streamich/react-use/issues/2224  see the reply

**Comment by joeljtomy** [comment]
## That's the normal behaviour, as described here 
- https://github.com/imbhargav5/rooks/blob/76426161edca1f233c8d4dea6ce5e5f97d4ff607/packages/rooks/src/hooks/useLocalstorageState.ts , data is serialized / deserialized before beeing sent / get back to / from local storage, and the default serializer and deserializer are JSON.stringify and JSON.parse.
