### ISSUE TITLE
useKeys – key map not cleared if window loses focus

### ISSUE THREAD

**Issue by CiaranMn** [imbhargav5/rooks#1730]
**Description**

If the window loses focus, the `keyup` handler is not called and therefore any keys that were held while the window loses focus are still thought to be held when it regains focus.

I believe this is the issue underlying https://github.com/imbhargav5/rooks/pull/1210 which fixed it for specific cases of focus being lost, but there are many more, e.g.:
1. User presses CTRL + F: when re-focusing the window, CTRL + F are still tracked as pressed ([codesandbox](https://codesandbox.io/s/happy-panini-s9yh6y?file=/src/App.js))
2. Users holds a key and clicks another tab
3. Various other browser hot keys which cause the window to lose focus, e.g. for downloads in Chrome `⌘ + Shift + j` or `ctrl + j`

**Solution**
The simplest solution is to have a `blur` handler on the window which wipes the `PressedKeyMapping`.

I believe the code for overwriting `alert` etc can then be removed (but have not tested it).

**Comment by coycoylaniba** [comment]
what's the status for this?
