### ISSUE TITLE
use*Storage does not provide type support

### ISSUE THREAD

**Issue by aappddeevv** [imbhargav5/rooks#174]
**Is your feature request related to a problem? Please describe.**
Presumably to allow any key/object combination, use*Storage does not take a type parameter.

**Describe the solution you'd like**
Export interfaces so we can at least type the hook more easily, `use*Storage(...) as StorageHandler<MyObject>` or allow the type of object to be stored to be specified e.g. `use*Storage<MyObject>(...)`.

**Describe alternatives you've considered**
Described above.

**Additional context**
Otherwise, I have to add some ugly type castings if I want something more specific than any.

**Comment by imbhargav5** [comment]
Hi @aappddeevv I am not familiar with interfaces as much. Would you like to submit a PR?
