### ISSUE TITLE
mousedown support for use-outside-click(-ref)

### ISSUE THREAD

**Issue by IllusionMH** [imbhargav5/rooks#199]
**Is your feature request related to a problem? Please describe.**
We are using D'n'D list with ability to modify elements right in the list using double click. Click on Cancel or outside of item. However when item is in edit mode can press left mouse button on any other item in list, drag it and item in edit mode won't be converted to view mode.

**Describe the solution you'd like**
Currently these hooks [use `click` event](https://github.com/imbhargav5/rooks/blob/1e950073f9a14023c36923736c70432761c3cc0a/packages/outside-click/src/useOutsideClick.ts#L31). In our case it will be preferable to use `mousedown` to fix this problem.
Options are:
1) Replace `click` with `mousedown` for everyone (not sure if this won't break existing usages)
2) Add third parameter to hook that will switch from `click` to `mousedown` if `true`
3) Same as above but replace `when` parameter with object `{isEnabled: boolean, mousedown: boolean}`, similar to `addEventListener`'s third parameter.

**Describe alternatives you've considered**
We'll patch events locally or write own hook implementation.

**Additional context**
While switch from `click` to `mousedown` fixes described problem with mouse events, it looks like similar problem can be reproduced with touch (tested Windows 10, Edge 79 (Chromium)). Change of event will bring asymmetry between touch and mouse in this aspect.

Switch to `pointerdown` in future will cover all cases. [Pointer Events API support](https://caniuse.com/#feat=pointer)

I can submit PR if any of 3 options works for you.

**Comment by imbhargav5** [comment]
Let’s try 2? Feel free to send a PR!

**Comment by maciekgrzybek** [comment]
Is anyone working on this one? If not I can give it a go :)

**Comment by IllusionMH** [comment]
Sorry for slow progress here. I faced problem with handling cases when third argument changed between renders.
Not clear if it should be ignored or event listeners updated.

@maciekgrzybek I think I would be able to continue work this weekend, however if you need this earlier or has own ideas for implementation - just ping me so we won't do same twice. Thanks.

**Comment by maciekgrzybek** [comment]
@IllusionMH no problem mate :) I just thought that no one is working on this one :)

**Comment by IllusionMH** [comment]
@maciekgrzybek submitted the PR, but need to move tests to PR

**Comment by imbhargav5** [comment]
Hey I will be back in a week or so. Getting married this week. 🙏

**Comment by IllusionMH** [comment]
WOW! Congratulations! 🎉  Have a great time.

I'll try to add new StoryBook examples then.
