### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by ketewan** [imbhargav5/rooks#207]
Thanks for developing this library!

**Describe the bug**
I tried to use useMutationObserver, it worked great everywhere except for IE11, where it produces syntax error. I also tried to open the storybook (https://stories.react-hooks.org/) in IE11, and it has similar issue. If I just copy the code of the hook to my project, it works without any problems on IE11 too, so I guess it's a build issue. I did not find any disclaimer about not supporting IE. Are you intentionally not supporting this browser or is this a bug?

**Screenshots**
Here what is in console for storybook
![rooks](https://user-images.githubusercontent.com/31967149/75339029-c7e66c00-58a0-11ea-8cc0-bb9969ae57a5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Comment by imbhargav5** [comment]
I see. It's probably because IE11 doesn't support mutation observer. I am not sure to be honest.

**Comment by ketewan** [comment]
@imbhargav5, mutation observer is supported by IE11 https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by maciekgrzybek** [comment]
@imbhargav5 not sure what's your thoughts on this, but I'm a massive advocate of stop supporting IE11 :)

**Comment by imbhargav5** [comment]
Yeah I think at this point even Microsoft doesn't care about IE anymore.
