### ISSUE TITLE
Use react-hooks-testing-library for testing

### ISSUE THREAD

**Issue by chrismilson** [imbhargav5/rooks#211]
**Is your feature request related to a problem? Please describe.**
Im frustrated when I read the tests that have a roundabout way to test interaction with a hook. 

For example:
- In the test for usePrevious hook, there is a click handler that updates the value on the state of a dummy object. There is no indication from the test what the click will do to the hook.

- In the tests for useCounter, a dummy component is mocked up with buttons that act as a proxy to the api that the hook returns. By using the testing library, the returned methods could be directly called in the test instead of seeing button clicks.

**Describe the solution you'd like**
I'd like the tests that don't need an explicit parent component to be tested to have their tests written with [react-hooks-testing-library] (it's already used for the tests on the countdown hook).

I can do a pr for these changes.

**Describe any alternatives**
We could leave the tests as is and have to read a lot more to understand what they actually do.

**Comment by imbhargav5** [comment]
@chrismilson Sounds good! Let's do that!
