### ISSUE TITLE
Remove unnecessary hooks from navigator-language hook

### ISSUE THREAD

**Issue by chrismilson** [imbhargav5/rooks#212]
**The problem**
The useNavigatorLanguage hook uses state and effect hooks that cause unnecessary updates to a component.

**Possible solutions**
Retrieving the readonly property language from the navigator is not computationally intensive; just return the value as it is.

We could also just wrap the value in a closure and store it locally if navigator.language is too slow (it probably isn't).

**Other information**
I can do a pr for this.

**Comment by imbhargav5** [comment]
@chrismilson Thanks for creating an issue! Yes please feel free to submit a PR!
