### ISSUE TITLE
Add useDebugValue to hooks for easy debugging.

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#23]

**Comment by bradd123** [comment]
https://reactjs.org/docs/hooks-reference.html#usedebugvalue

Do we need to add this to all the hooks?

**Comment by imbhargav5** [comment]
Yes definitely!

**Comment by maciekgrzybek** [comment]
I could add that, if you guys still need help :)

**Comment by imbhargav5** [comment]
Definitely. Feel free to take it up!

**Comment by maciekgrzybek** [comment]
Hey, sorry it's been a while, but I've got time to tackle this task finally. I'm reading the docs, but there's a fragment:
```
Tip

We don’t recommend adding debug values to every custom Hook. It’s most valuable for custom Hooks that are part of shared libraries.
```
Are you sure to add it to the project?

**Comment by imbhargav5** [comment]
Yeah now that I see this, I am actually fine with ignoring this issue for now. 👍

**Comment by maciekgrzybek** [comment]
Make sense? :)any other tickets to sort out?

**Comment by imbhargav5** [comment]
@maciekgrzybek Sure! There is a small issue here https://github.com/imbhargav5/rooks/issues/86. But if you like to you can create a `useThrottle` hook similar to `useDebounce` which we have. What do you think?

**Comment by maciekgrzybek** [comment]
hey @imbhargav5 , I'll jump into this fix first :) could you tell me how to get the local environment to work? I'm trying different commands from package.json but no luck :(

**Comment by maciekgrzybek** [comment]
@imbhargav5 nevermind, my laptop was being an asshole :D figure it out now :)

**Comment by maciekgrzybek** [comment]
PR added - https://github.com/imbhargav5/rooks/pull/87

**Comment by maciekgrzybek** [comment]
Also, I can jump into that next one - I'll create a ticket :)
