### ISSUE TITLE
initialize `useWindowSize` with real values rather than `null`

### ISSUE THREAD

**Issue by sebpiq** [imbhargav5/rooks#233]
When using `useWindowSize` since [it first initializes](https://github.com/imbhargav5/rooks/blob/master/packages/window-size/src/useWindowSize.ts#L25) with `null` values and then gets the real values in a `useEffect`, it means that any component that uses the hook will render at least twice, for no good reason. Is there a good reason for the current implementation?

**Comment by imbhargav5** [comment]
Hi @sebpiq This issue was fixed recently. Sorry I took ages to get to this one.
