### ISSUE TITLE
[useDebounce] Can't find variable Event

### ISSUE THREAD

**Issue by svenlombaert** [imbhargav5/rooks#235]
**Describe the bug**
When I use the `useDebounce` hook on react-native, an error is thrown. `Can't find variable Event`

**Expected behavior**
I would think this hook would work on react-native

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.

**Additional context**
Using React Native. (0.60.x)

**Comment by imbhargav5** [comment]
Fixed today.
