### ISSUE TITLE
Use `useEffect` instead of `useLayoutEffect` for raf hook

### ISSUE THREAD

**Issue by weotch** [imbhargav5/rooks#236]
**Is your feature request related to a problem? Please describe.**
When SSRing, like with Next.js, the `raf` hook warns:

>Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.

**Describe the solution you'd like**
No warning message

**Describe alternatives you've considered**
Switching to a different `raf` hook that uses `useEffect`

**Additional context**
This is similar to #86.  If I understand the difference between `useEffect` and `useLayoutEffect` correctly, I `useEffect` would be fine for `raf`.

**Comment by imbhargav5** [comment]
Hi @weotch , but `useEffect` will be more delayed than `useLayoutEffect` wouldn't it? I personally think, components which need to use `useRaf` shouldn't render on the server, since they don't contribute anything on the server side.

**Comment by weotch** [comment]
> Hi @weotch , but useEffect will be more delayed than useLayoutEffect wouldn't it?

I wouldn't _think_ so.  From [the docs](https://reactjs.org/docs/hooks-reference.html#uselayouteffect):

> The signature is identical to useEffect, but it fires synchronously after all DOM mutations. Use this to read layout from the DOM and synchronously re-render. Updates scheduled inside useLayoutEffect will be flushed synchronously, before the browser has a chance to paint.
> Prefer the standard useEffect when possible to avoid blocking visual updates.

That description reads to me like using `useEffect` would be more appropriate for animations (which I'm assuming is the primary use case of `useRaf`).

**Comment by imbhargav5** [comment]
Got it. Will do. Sorry I got back so late. Will do this change.

**Comment by imbhargav5** [comment]
Fixed.
