### ISSUE TITLE
IE11 webpack vendor error

### ISSUE THREAD

**Issue by porteron** [imbhargav5/rooks#250]
Two npm libraries our project use reference `/@rooks/use-outside-click`. 

The webpack build is throwing an error in **IE11**.

**ERROR**:
` Expected ')'`

<img width="1101" alt="Screen Shot 2020-08-21 at 7 55 34 PM" src="https://user-images.githubusercontent.com/16027973/90947132-4b17f300-e3e8-11ea-8dfc-51a07f35b853.png">

**Comment by imbhargav5** [comment]
Hi @mnoster , I am not really sure what the cause of this error is though. The hook is pretty simple and perhaps the way webpack is building it, might be an issue?

**Comment by victorcfernandes** [comment]
Hi @imbhargav5 I had the same issue with useLocalstorage. Exactly the same error as above

**Comment by imbhargav5** [comment]
Any idea what the error could be? I am actually lost 😅
