### ISSUE TITLE
[useFullscreen] useFullscreen is not SSR-friendly

### ISSUE THREAD

**Issue by gpoole** [imbhargav5/rooks#260]
**Describe the bug**
`useFullscreen` directly accesses `document` so can't be used with server-side rendering. Errors produced are e.g.

```
ReferenceError: document is not defined
```

**To Reproduce**
Use SSR with a component that calls `useFullscreen`:

```js
const { renderToString } = require('react-dom/server');
const useFullscreen = require('@rooks/use-fullscreen');

renderToString(() => {
  useFullscreen();
  return <></>;
});
```

**Expected behavior**
`useFullscreen` should probably do a 2-pass render, with the first pass (server-side render and browser initial render) having fullscreen support off and a second (browser only) if fullscreen support is detected for the browser.

**Comment by maciekgrzybek** [comment]
I'll take a look at this one tomorrow

**Comment by maciekgrzybek** [comment]
A little bit later... but PR -> https://github.com/imbhargav5/rooks/pull/344  @imbhargav5

**Comment by imbhargav5** [comment]
#344 fixes this.
