### ISSUE TITLE
useFullscreen becomes out of step with state when exiting using "ESC" key

### ISSUE THREAD

**Issue by danielholmes** [imbhargav5/rooks#278]
**Describe the bug**
I've been testing on Google Chrome. When you enter full screen by calling `request`, you see a message saying you can exit full screen by pressing `ESC`. If you do press `ESC` then the `isFullscreen` state returned by `useFullscreen` is still `true`.

**To Reproduce**

See https://github.com/danielholmes/rooks-fullscreen-issue for an illustration of the error.

1. Set up `useFullscreen` hook (e.g. `const fs = useFullscreen();`)
2. Call `fs.request()`
3. Once in fullscreen mode, press `ESC` key
4. `fs.isFullscreen` is incorrect

**Expected behavior**
`isFullscreen` should return false after user has pressed `ESC` to exit fullscreen

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome (possibly an issue with other browsers, haven't checked)
 - Version: 86 

**Additional context**
I'm using the following patch atm, which seems to work, but I don't feel confident submitting a PR for it as I haven't tested it much or on many browsers:

```
diff --git a/node_modules/@rooks/use-fullscreen/lib/index.esm.js b/node_modules/@rooks/use-fullscreen/lib/index.esm.js
index b60f9b0..4dafb9a 100644
--- a/node_modules/@rooks/use-fullscreen/lib/index.esm.js
+++ b/node_modules/@rooks/use-fullscreen/lib/index.esm.js
@@ -69,6 +69,14 @@ var useFullscreen = function () {
                 setIsFullscreen(true);
                 off("change", onFullScreenEntered);
                 resolve();
+
+                var onExitCheck = function (e) {
+                  if (!document.fullscreenElement && !document.webkitIsFullScreen && !document.mozFullScreen && !document.msFullscreenElement) {
+                    setIsFullscreen(false);
+                    off("change", onExitCheck);
+                  }
+                }
+                on("change", onExitCheck);
             };
             on("change", onFullScreenEntered);
             element = element || document.documentElement;
```

**Comment by imbhargav5** [comment]
@danielholmes Will fix this before I release v4 in a few days. Currently working non stop on rooks.

**Comment by simbathesailor** [comment]
@imbhargav5 : I tried to fix the issue in this codesadnbox https://codesandbox.io/s/wizardly-star-m92ky?file=/src/App.js. Let me know if it's is acceptable. I will raise the pr for this issue.

**Comment by zamarawka** [comment]
@imbhargav5 any updates on this issue?? I faced with it on 4.7

**Comment by imbhargav5** [comment]
@zamarawka My immediate priority is full screen hook. Will fix it this week. Thanks for your patience.

**Comment by imbhargav5** [comment]
Add a patch similar to this today @zamarawka and @danielholmes

**Comment by imbhargav5** [comment]
#344 fixes this.

**Comment by imbhargav5** [comment]
v4.8 is out. And fullscreen hook works well now. @danielholmes 

Here is a sandbox you can try https://codesandbox.io/s/immutable-wave-m87bx?file=/src/App.js
