### ISSUE TITLE
useKeys wrong type

### ISSUE THREAD

**Issue by AdrienLemaire** [imbhargav5/rooks#279]
**Describe the bug**
The hook type does not match the function definition.
Definition:
```ts
function useKeys(keysList, callback, opts) {}
```
Type
```ts
export default function useKeys():void
```

![](https://i.imgur.com/K6vUfJM.png)

using @rooks/use-keys@3.6.0

**Comment by AdrienLemaire** [comment]
React also breaks with error `Too many re-renders` when trying to use useKeys. I do not have this problem with useKey.

```ts
const keyDownOptions = {
  eventTypes: ["keydown"],
  when: true,
};

const MyComponent: React.FC<> = () => {
  const [direction, setDirection] = useState("");
  useKeys(["ArrowLeft", "ArrowUp"], setDirection("upLeft"), keyDownOptions);
  ...
};
```
I thought it might be because of `when: true`, but removing the options still throws the same error.

**Comment by imbhargav5** [comment]
Hmm looks like `useKeys` is having a few. I am doing a major refactor right now. Will be releasing v4 with fixes this month.
