### ISSUE TITLE
Update homepage here to point to the hooks documentation page

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#282]
![Screenshot 2020-11-18 at 10 54 25 AM](https://user-images.githubusercontent.com/2936644/99487520-8fd20c80-298c-11eb-9639-f9c6684a2b60.png)

For eg: in the image above, the home page is pointing to stories.stuff. We should point it to https://react-hooks.org/docs/use-mutation-observer.

We need to edit the package.json of all hooks in the same way to get this done.

**Comment by calthejuggler** [comment]
So, I changed it, but I'm not sure if I made the pull request right! Hope it helps 😋 #284

**Comment by jorisw** [comment]
It would help if you did the same for the GitHub link actually. Linking to the monorepo confused me into thinking I followed the wrong link.

**Comment by imbhargav5** [comment]
For sure. I am going to open an issue for the same. Please consider sending a PR if that's not too much trouble. Have a lot lined up to publish this week for v4.
