### ISSUE TITLE
Upgrade to yarn v2

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#303]
We are currently using yarn v1. Moving to yarn v2 might be painful but is worth a ton!

**Comment by maciekgrzybek** [comment]
I can try :)

**Comment by maciekgrzybek** [comment]
Hey, @imbhargav5 I've tried to figure this ticket out, but no luck. I think I'd need more understanding of the project to do it :( sorry :(

**Comment by imbhargav5** [comment]
Yeah. Don't worry about this for now @maciekgrzybek. This is a very tough task and we can postpone this for v6 or v7.
