### ISSUE TITLE
Algolia search is currently not configured well

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#312]
There is some work going on in docusaurus repo. Once that is fixed we need to configure algolia well. 

https://github.com/facebook/docusaurus/issues/3826

**Comment by slorber** [comment]
Hi,

For what it's worth we just had a regression on master, but the latest release does not have major search issue normally

**Comment by imbhargav5** [comment]
@slorber  

Actually I faced the same issue on my end even in the previous version. I think it was v67 . 
Contextual search + facetFilters never quite worked well for me. I was able to view my search results well in the Docsearch playground but somehow docusaurus was returning empty results until I did this today. https://github.com/imbhargav5/rooks/pull/311/files
I don't know if my config here is an exception but I only got search to work after I disabled 'facetFilters'. 
Thanks for letting me know anyway :) Docusaurus is amazing!

**Comment by slorber** [comment]
Hi,

Contextual search = computing facet filters dynamically.

The upcoming release (than you can try using the `@canary` new tag) will have the ability to "merge" the user-provided facets with the dynamically computed facet  (https://github.com/facebook/docusaurus/pull/3804)

However `'facetFilters': ["type:$TYPE"]` looks bad to me. You can't use `$TYPE`, you have to use your real facet value here, not a placeholder. We don't have any logic to replace $ prefixed variables, these  filters are passed as provided to Algolia.

**Comment by imbhargav5** [comment]
Will try this.
