### ISSUE TITLE
Show contributors in home page

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#313]
- We basically need to populate a file called contributors.md or something like that at /packages/docusaurus/docs/contributors.md and use it in our homepage. 
- Update the file in our PR release workflow

**Comment by Avi98** [comment]
Hi @imbhargav5 can I work on this

**Comment by imbhargav5** [comment]
For sure!

**Comment by Avi98** [comment]
Hi @imbhargav5  do you want me to maintain a hardcoded file called contributor.md or to write a script using that extracts the contributors from .all-contributorsrc.

**Comment by imbhargav5** [comment]
So we need to generate a contributors.md inside the docusaurus package using all contributors cli within our script. 

We can use the same script to update our readme.
