### ISSUE TITLE
[useIntersectionObserverRef] Double trigger or am I doing something wrong?

### ISSUE THREAD

**Issue by rfgamaral** [imbhargav5/rooks#331]
I'm trying to use `useIntersectionObserverRef` to detect when an element with `overflow-y: scroll` reaches the top/bottom and I have managed to do so but I'm observing an unexpected behavior. I'm not sure if I'm doing something wrong but there's a working demo with 2 implementations: https://codesandbox.io/s/quizzical-smoke-djqbu

The default one uses `@rooks/use-intersection-observer-ref` and the alternative uses [`react-intersection-observer`](https://github.com/thebuilder/react-intersection-observer). You can switch between implementations by commenting/uncommenting the appropriate line in the `index.js` file.

Both implementations have 1 `console.log` statement and here lies the problem. The "rooks" implementation prints the log **twice**, the alternative method prints **only once**, as I believe it should be.

Am I doing something wrong here? Is the hook tirggering twice, for some reason?

**Comment by imbhargav5** [comment]
Hey @rfgamaral, 

At first glance, this looks like a bug. Will take a look!

**Comment by maciekgrzybek** [comment]
I'm not entirely sure if I'm right but I think it's not a bug, in two different callbacks you're changing two different pieces of state (`isTopOverflowing` and `isBottomOverflowing`). This means if one of them will change it will re-render the components, hence double logging. If you want to track just one of them, use `useEffect` with the desired state as a dependency:
`useEffect(() => {
  // do whatever you need with isTopOverflowing
}, [isTopOverflowing])`

Hope that helps :) Let me know if you need more assistance/explanation @rfgamaral  :)

**Comment by rfgamaral** [comment]
I'm so sorry, but I'm not using this hook anymore, I just wanted to report what _I thought_ was a bug. If it's not, let's close it :)

**Comment by maciekgrzybek** [comment]
It's perfectly fine mate :) thanks for taking your time to report this :)
