### ISSUE TITLE
Adding prettier 

### ISSUE THREAD

**Issue by maciekgrzybek** [imbhargav5/rooks#345]
What are your thoughts on adding `prettier` to the project? Would be a nice DX improvement.

**Comment by imbhargav5** [comment]
Sure, we can!

**Comment by maciekgrzybek** [comment]
Awesome, I'll try to add it (I'll tackle yarn upgrade first, so don't assign me yet in case anyone else wants to do it)

**Comment by harshilparmar** [comment]
Can I try this !!

**Comment by maciekgrzybek** [comment]
Sure thing, go for it mate :) let us know if you need any help :)
