### ISSUE TITLE
Ideas for more hooks!

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#36]
Hi Community!,

What kind of hooks do you want to see? Let's pitch some ideas here and take them up!

**Comment by Dianoga** [comment]
I'd like to see a `useDebounce` hook like this one https://github.com/streamich/react-use/blob/master/src/useDebounce.ts. 

I was going to submit a PR, but the mono-repo stuff is blocking me and I don't have time to figure it out right now. The `react-use` library is under `unlicense` so you should be able to bring it in directly if you decide you like the idea.

**Comment by imbhargav5** [comment]
Definitely. Can you explain what is making it difficult for you to contribute? I will document it for everyone.

**Comment by Dianoga** [comment]
I was able to create the hook via `yarn create`, but I don't know what needs to be done to get the new hook into the rooks package. Also, normally to test npm packages where I want to use them, I can just symlink the package into `node_modules` but in this case it wasn't obvious what should be linked.

**Comment by simbathesailor** [comment]
Maybe a hook which listens for multiple key presses and does something when certain keys are pressed at a time.
I created a hook for listening to multiple keypress shortcuts on a page or any dom element where key press makes sense in this library. https://github.com/simbathesailor/react-key-collector .  I think this repo is suitable place for this hook
Maybe I can raise a pr for it after having discussions ?.

**Comment by imbhargav5** [comment]
Definitely go ahead! Perhaps we can make a useKeys hook 🤔 ?

**Comment by simbathesailor** [comment]
Cool , i will raise a pr asap and we will take it from there.

**Comment by simbathesailor** [comment]
Hi @imbhargav5 
I was working on some react project, and somehow found a need for getting geolocation.
Can we have something called useGeolocation(). Most of the time its like a utility that get called when someone clicks on use my location text. But do we have any usecases where we need to have geolocation info(lat and lng ) on component mount or updates or something? What are your thoughts?

**Comment by simbathesailor** [comment]
@imbhargav5 
How about of hook which provides the history of any variable.(useHistory) It can be used to implement undo functionality for lot many cases. 
Similar to https://github.com/omnidan/redux-undo.
 
 We have usePrevious but that  work for just previous value. 
Your thoughts ?

**Comment by imbhargav5** [comment]
I think implementing useUndo might be a touch too much for this project since useUndo needs to track every state or props change in the app which we can't control. Redux surrounds the app so it would make sense to be part of the react-redux project.

**Comment by simbathesailor** [comment]
How about having useImagePreview. A simple hook that gives you the blob image URL for dragged or selected image.  The use case is very common for the image upload websites, back-office application where banners are uploaded for a site, profile image uploads. It's a rough idea for now but can make it slimmer based on discussions. What are your thoughts?

**Comment by simbathesailor** [comment]
Sorry by mistake closed the issue

**Comment by imbhargav5** [comment]
@simbathesailor Interesting idea. We can do something like `useFileDrop`? And access the information of the file that was dropped within a ref.

**Comment by simbathesailor** [comment]
Hey @imbhargav5 , 
I was recently playing around with image zoom functionality, that we generally see on e-commerce websites, similar in flipkart website. I created a useImageZoom hook. Here is the link to codesandbox:  https://codesandbox.io/s/useimagezoom-ihvh5 . Please have a look at it and let me know, if we can take up this and improvise on it.

**Comment by simbathesailor** [comment]
@imbhargav5 , I came up with useDoubleClick hook. Can it be part of rooks package. There is no css involved. Right now it is not using useTimeout. But I can make changes to do so. I am also planning to write an article on it, where i can also mention about rooks package. Should i go ahead and do that. 

[https://codesandbox.io/s/suspicious-brown-q9t59](url)

**Comment by imbhargav5** [comment]
Yep @simbathesailor Lets add it!

**Comment by lokeshpathrabe** [comment]
@imbhargav5 I created a custom hook I call useConditionalEffect. This is mostly for replacing the conditional execution of code inside a useEffect callback. Something like below.

```
const prevFilters = usePrevious(filters);

 useEffect(() => {
  if(!isEqual(prevFilters, filters)){
     ..... some code here
   }
 }, [list, filters])
```
This can be replaced with a custom hook like below.
`useConditionalEffect(() => { .... some code here}, [list, filters], [filters])`
Check the codeSandBox here https://codesandbox.io/s/usememoeffect-pbh4x?file=/src/App.js
Let me know what you think about this. I will open a PR accordingly.

**Comment by imbhargav5** [comment]
@lokeshpathrabe Sorry man. I completely missed this. But a useEffect already runs when something changes doesn't it?

**Comment by lokeshpathrabe** [comment]
@imbhargav5 Yes you are correct. But useEffect uses simple equality checks for dependencies. When your dependencies are objects, useEffect will do object reference check there. This fails when reference changes but the object is basically the same. Causing effect to execute unnecessarily.

**Comment by rfgamaral** [comment]
Media queries? Breakpoints? Stuff like that... For inspiration: https://github.com/contra/react-responsive

**Comment by imbhargav5** [comment]
For sure. I have been thinking about this one. Will do something like this
soon.

**Comment by mrvisser** [comment]
> Media queries? Breakpoints? Stuff like that... For inspiration: https://github.com/contra/react-responsive


> For sure. I have been thinking about this one. Will do something like this soon.
> […](#)

@rfgamaral @imbhargav5 PR is available for media queries: https://github.com/imbhargav5/rooks/pull/409
