### ISSUE TITLE
useFullscreen toggle function is buggy

### ISSUE THREAD

**Issue by zamarawka** [imbhargav5/rooks#367]
**Describe the bug**
At last update of useFullscreen hook (4.8 version) "toggle" function not work as before. In `isFullscreen === true` state it doesn't exit from fullscreen.

**To Reproduce**
1. Go to sandbox
2. Click on "Fullscreen" button
3. Await fullscreen open
4. Click on "Fullscreen" button again
5. Nothing change -> unexpected behaviour

**Expected behavior**
"toggle" will exit from fullscreen state

**Screenshots**
https://codesandbox.io/s/interesting-shamir-708ci?file=/src/App.js

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome, safari
 - Version any

**Additional context**
Broken after #344 pr. Relates to #278

**Comment by imbhargav5** [comment]
You are right @zamarawka ! Looking into this now.

**Comment by imbhargav5** [comment]
Just made a fix. Will push if you can confirm it's working well @zamarawka 
Please take a look here. 
https://q4hpf.csb.app

**Comment by zamarawka** [comment]
@imbhargav5 yep, it looks like everything alright.
thanks for fast fix!
