### ISSUE TITLE
[use-navigator-language] listen to languagechange event

### ISSUE THREAD

**Issue by phaux** [imbhargav5/rooks#386]
**Is your feature request related to a problem? Please describe.**
I looked at the source code of that hook and it doesn't listen to language change.

**Describe the solution you'd like**
Listen to language change.

**Describe alternatives you've considered**
I wrote my own hook.

```js
function useLanguage() {
  const [language, setLanguage] = useState(navigator.language);

  useEffect(() => {
    function handleLanguageChange() {
      setLanguage(navigator.language);
    }
    window.addEventListener("languagechange", handleLanguageChange);
    return () => {
      window.removeEventListener("languagechange", handleLanguageChange);
    };
  });

  return language;
}
```

**Additional context**
I know that this event never actually fires unless you go to browser language settings and change something, but since it exists why not to use it.

It's great when you're translating your app and switching the language often. That way you don't have to refresh the app every time.

**Comment by maciekgrzybek** [comment]
Hey that's a really great idea :) would you like to implement it in the library?

**Comment by phaux** [comment]
Sure. I will do that when I find the time

**Comment by imbhargav5** [comment]
```

function useLanguage() {
  const [language, setLanguage] = useState( () => {
    if(typeof navigator !== "undefined"){
     return navigator.language
} else{
     return null // or any default
}
} );

  useEffect(() => {
    function handleLanguageChange() {
      setLanguage(navigator.language);
    }
    window.addEventListener("languagechange", handleLanguageChange);
    return () => {
      window.removeEventListener("languagechange", handleLanguageChange);
    };
  });

  return language;
}

```

Everything from @phaux looks good. I think we should just check if navigator exists in the useState initialiser like so. What do you think @maciekgrzybek ?

**Comment by maciekgrzybek** [comment]
Yep that looks good :)

**Comment by imbhargav5** [comment]
Just created a PR @phaux. Please let me know what you think!

**Comment by phaux** [comment]
@imbhargav5 Looks good, thanks!
