### ISSUE TITLE
fullscreen doesn't work anymore

### ISSUE THREAD

**Issue by AdrienLemaire** [imbhargav5/rooks#404]
**Describe the bug**
calling `request()` doesn't set the screen fullscreen anymore, when it did before.

**Additional context**
While debugging the code, it seems like `document.requestFullscreen` doesn't exist anymore on latest Chrome versions (currently on v89).
Executing `document.body.requestFullscreen()` does work though. Is chrome expecting an Element instead of a document now ?

**Comment by imbhargav5** [comment]
Wow. No idea how this happened. 😮 cc @simbathesailor

**Comment by simbathesailor** [comment]
Hmm I will have a look at it tomorrow

**Comment by AdrienLemaire** [comment]
@imbhargav5 @simbathesailor actually, requestFullscreen has never been supported on document. 
When looking at the last file diff, I noticed that you removed the default to request(). You used to pass `document.documentElement` if no element was specified

https://github.com/imbhargav5/rooks/commit/8798d55bc56308f7b3231b55cc210a49483faccc#diff-d57af082ea7e8bc8e6a5c48e35dc45d784299bf8715e1ce2ee43db1de25cf265

You removed that default, which is was my code broke when upgrading.

**Comment by simbathesailor** [comment]
@AdrienLemaire : You are right. Earlier this statement was making it work:

```
element = element || document.documentElement;
```

Would you like to raise a pr with the fix ?.

**Comment by AdrienLemaire** [comment]
Thank you!
