### ISSUE TITLE
Show hooks list in camelcase

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#428]
https://react-hooks.org/docs/hooks-list

**Comment by maciekgrzybek** [comment]
Is the `list-of-hooks.md` auto generated?

**Comment by imbhargav5** [comment]
Yes 👍

**Comment by imbhargav5** [comment]
@maciekgrzybek Hopefully you didn't make any progress on this, because I made a ton of changes in a different branch and I can wrap this up in the next two minutes.

**Comment by maciekgrzybek** [comment]
Yep, do it mate :)
