### ISSUE TITLE
Invalid hook call with useRaf + snowpack

### ISSUE THREAD

**Issue by jfrancos** [imbhargav5/rooks#450]
Thanks for a great system of hooks utilities!

**Describe the bug**
I'm using [snowpack](https://www.snowpack.dev/).  `useInterval` and `useTimeout` work as expected, but with `useRaf` I get the error:
> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

etc.

For the sake of experiment, I tried using useRaf with CRA, and did not have any issue.  So it seems to be specific to useRaf + snowpack.

**To Reproduce**
`npx create-snowpack-app raf-test  --template @snowpack/app-template-react`
`cd raf-test`
`npm install @rooks/use-raf`
`npm start`
Add `useRaf(() => {})` to the App function

**Expected behavior**
I expected useRaf to not result in an error about an invalid hook call.
 
Tagging snowpack's maintainer, in case he has any insights here @fredkschott

**Comment by imbhargav5** [comment]
Hmm, is it possible that you have two different versions of react installed? This bug definitely shows up in that case but not sure if that is the cause here.

**Comment by imbhargav5** [comment]
@jfrancos can you try this with rooks v5 and let me know? So instead of shipping individual packages it's just a single package from now on just to get rid of the enormous bottlenecks with lerna and yarn workspaces and also have semantic release + changelog + docs.

**Comment by jfrancos** [comment]
@imbhargav5 This indeed is no longer an issue now in v5.  Thanks!
