### ISSUE TITLE
Add redirect from old links to new camelcase links

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#470]
**Describe the bug**
Our old links eg `https://react-hooks.org/docs/use-did-mount` will no longer work since we are now using links with the hook names directly to avoid confusion. `https://react-hooks.org/docs/useDidMount`. 

Let's add docusaurus redirects to make sure people using the older v4 individual hooks continue to see the docs.

**Comment by qiweiii** [comment]
@imbhargav5  Could i try this?

**Comment by imbhargav5** [comment]
@qiweiii Go for it!
