### ISSUE TITLE
New hook request : useKeyBindings

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#473]
Let's create a new hook that looks like this. 

```javascript

useKeybindings(
   1 => callback1,
   2 => callback2,
   'Enter' => callback3
)

```
So basically this is a multi version of `useKey` but also has a better structure. 

Source : Found inspiration for this on http://joshwcomeau.com/

Please read docs for contributing here if you are new 😄 https://github.com/imbhargav5/rooks/blob/main/CONTRIBUTING.md

**Comment by harshilparmar** [comment]
I would like to work on this one !! 
(question) : As I understand this, here We have to make a hook that takes multiple event handlers at once right?

**Comment by imbhargav5** [comment]
Yep that's right @harshilparmar . This should be a great exercise for you. Take it up! 🚀

**Comment by harshilparmar** [comment]
@imbhargav5 Can you please tell me how to create a new hook setup. I have tried `yarn new` but it's not working!!

**Comment by imbhargav5** [comment]
@harshilparmar Can you send a loom of this issue? You can make a short clip using http://loom.com.

**Comment by harshilparmar** [comment]
I have tried loom but it's taking too much time to play
attaching a snapshot of this behavior.
![image](https://user-images.githubusercontent.com/45915468/117416051-9ce0b900-af36-11eb-809c-7ff2292351cc.png)

**Comment by imbhargav5** [comment]
Oh wait, looks like you are not in the `main` branch. You seem to be in `master`

**Comment by imbhargav5** [comment]
@harshilparmar

**Comment by harshilparmar** [comment]
@imbhargav5 Hey can you  please guide me here 
My approach for this is 
1. Take arguments array
2. loop through that array for further process

**Comment by imbhargav5** [comment]
Yep that is correct @harshilparmar

**Comment by harshilparmar** [comment]
@imbhargav5 Can you please assign this to someone else It is taking much time for me to figuring out this 😅

**Comment by imrishabh18** [comment]
Hey @imbhargav5 ! Can I take up this issue? It would be nice to see how to make a Hook 😃

**Comment by imbhargav5** [comment]
a PR is already open I believe . Could you take it close?

**Comment by imbhargav5** [comment]
@imrishabh18 I believe a PR is open but it would be great if you can take it to close. Would appreciate that a lot! https://pop.com/l/add-contact?link=-MbzAzslM-SXHajSQFGT

**Comment by imbhargav5** [comment]
Merged.
