### ISSUE TITLE
Pass array of elements to useOutsideClick

### ISSUE THREAD

**Issue by maciekgrzybek** [imbhargav5/rooks#482]
**Is your feature request related to a problem? Please describe.**
I had to use `useOutsideClick` hook equivalent at work, but I had to pass more than one element as an argument. I came up with a nice solution where you can either pass an element or array of elements. I will gladly at this to our hook. Thoughts?

**Describe the solution you'd like**
Ability to pass an array of elements. Non-breaking change.

**Comment by imbhargav5** [comment]
Oh this seems like an edge case. Wouldn't it be simpler if we just it twice?

```jsx

useOutsideClick(ref1, f)
useOutsideClick(ref2, f)
```

**Comment by maciekgrzybek** [comment]
No, that doesn't work unfortunately as the two of them are not aware of each other.

**Comment by imbhargav5** [comment]
Oh? 🤔 Would you mind doing a quick code sandbox reproduction? I didn't understand the issue buddy @maciekgrzybek

**Comment by maciekgrzybek** [comment]
Yeah sure thing, I'll create something later :)

**Comment by vaishal** [comment]
Hi, I was about to raise a similar issue. I ended up creating my own hook to also address the `ontouchstart` + React v17 issue.

@imbhargav5 here's an example use-case https://codesandbox.io/s/useoutsideclick-multiple-refs-mb8hp
Without multi ref support clicking on either child closes them.

 I'm also happy to submit an MR to allow an array or single ref.
