### ISSUE TITLE
Cumulative typedefs for Rooks package

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#49]
We need to merge typedefs across all the individual packages and add them to the `rooks` package for autocompletion to work correctly.

**Comment by simbathesailor** [comment]
Hi @imbhargav5,
Could you please explain this issue more, I am a beginner in typescript. Would love to understand this problem and try this out.

**Comment by imbhargav5** [comment]
So our typedefs aren't really that great and they don't show up as often as we would like with autocomplete in VS code. Some definitions show up with `@rooks/useDidMount` but they won't show up for `import {useDidMount} from 'rooks' `. We need to find a way to combine typedefs well so the definitions are always visible.
