### ISSUE TITLE
useWindowSize SSR compatibility

### ISSUE THREAD

**Issue by allan2** [imbhargav5/rooks#492]
`useWindowSize` doesn't work with SSR. For example, it won't work with Next.js.
The window size is undefined on the server so there will be a warning like:

```
Warning: Expected server HTML to contain a matching <a> in <div>.
```

Suggestion:
 - The hook should check if `window` is `undefined`.

**Comment by imbhargav5** [comment]
Hi @allan2 , pretty sure we are already doing that. 
https://github.com/imbhargav5/rooks/blob/main/src/hooks/useWindowSize.ts#L35

**Comment by allan2** [comment]
[Here are some MWEs on this](https://github.com/allan2/window-hook-examples-for-ssr).

Example 1 is the rooks `useWindowSize` hook.
If you open the page on the dev server, you'll see the hydration error I'm talking about.

I opened #493 with my fix (also in Example 5). It actually removes the check if window is undefined.

I'm still not sure why it only shows up in the dev server.

**Comment by imbhargav5** [comment]
Hi @allan2 can you help me with a code sandbox ? You can host your project on a code sandbox and I will come up with a fix if there is a bug.

**Comment by allan2** [comment]
@imbhargav5

https://35k2z.sse.codesandbox.io/

This is a a clone of [my MWE repo](https://github.com/allan2/window-hook-examples-for-ssr).

**Comment by equinusocio** [comment]
I have the same issue with `useWindowScroll`. It seems that the window check is missing inside this hook,

**Comment by allan2** [comment]
[Josh Cormeau wrote an excellent article on this](https://www.joshwcomeau.com/react/the-perils-of-rehydration/#a-noble-but-flawed-attempt).
Taken from the article:

**A noble but flawed attempt**
In the shared code snippet, we attempt to solve for this problem in the first few lines:

```JSX
const Navigation = () => {
  if (typeof window === 'undefined') {
    return null;
  }
```

The idea here is sound: Our initial compile-time build happens in Node.js, a server runtime. We can detect whether or not we're rendering on the server by checking to see if window exists. If it doesn't, we can abort the render early.

The problem is that in doing so, we're breaking the rules. 😬

**Comment by imbhargav5** [comment]
I see. Thanks @allan2 and @equinusocio for this. I will take a closer look tomorrow!

**Comment by imbhargav5** [comment]
@allan2 I am confused. The only reason you see the issue is when the window size is greater than 1000. If it's less than 1000, you won't see the warning. Right? Let me know if I am missing something.

**Comment by allan2** [comment]
I am looking for correct rehydration on SSR when conditionally rendering on initial page load.

What do you think of the working examples I provided?

**Comment by imbhargav5** [comment]
I think the examples in this case make it break. for eg. I just forked your sandbox and removed innerWidth limit condition 
and it works. 
![Screenshot 2021-05-24 at 4 38 40 PM](https://user-images.githubusercontent.com/2936644/119339176-819fd880-bcae-11eb-86e6-19b9a8fe45d5.png)

https://ltj6l.sse.codesandbox.io/6

**Comment by allan2** [comment]
The issue is hydration with conditional rendering. Here, the condition is the window size so we can't remove that.

**Comment by imbhargav5** [comment]
Conditional rendering isn't an issue here but using a condition like `1000px` when on the server side we don't know the dimensions of the browser is the problem. 

Two pass rendering increases Time To First Paint, which not many people prefer. Having said that you can still add an extra condition on your end. 

```
return <div>{(typeof window === 'undefined' ||  ( innerWidth && innerWidth > 1000 ))  ? 'a' : 'b'} </div>
```

**Comment by allan2** [comment]
I should've said dynamic rendering.

It can be done without two-pass too. Set it not to not render initially but force the first render during useEffect.

If you disagee and think the current way is not a problem, then I will just close this.

**Comment by imbhargav5** [comment]
Yeah I am trying to understand your issue and find a solution as much as possible but the problem with this is that, 
a) existing hook can be slightly used differently to solve your case
b) if the hook is changed according to your fix, then a single render on client is not possible anymore

😅

**Comment by allan2** [comment]
Doing it once in useEffect is one pass on both client and server, no?

**Comment by imbhargav5** [comment]
It is two pass on the client, and one pass on the server because on the initial render it is `null`, then the useEffect updates state and it renders again with the new updated state variable.
