### ISSUE TITLE
The useInterval hook creates an undesired closure over the state.

### ISSUE THREAD

**Issue by fhellwig** [imbhargav5/rooks#50]
**Describe the bug**
The `useInterval` hook does not follow the [recommended approach from Dan Abramov](https://overreacted.io/making-setinterval-declarative-with-react-hooks/). As a result, it maintains the closure over outside objects used in the callback function. For example, using the state returned by `useReducer` in the `useInterval` callback will result in the callback function never seeing any updated state.

**To Reproduce**
1. Call `useReducer` to create a state.
2. Call `useInterval` to call an `increment` action on the state (via the `reducer`).
3. Print out the state in the `useInterval` callback function.
4. Observe that the logged state never changes.

**Expected behavior**
That the state seen in the `useInterval` callback should reflect the current state.

**Comment by imbhargav5** [comment]
@fhellwig I remember testing it a few times but didn't run into this issue. But will definitely want to solve this bug. Can you link a codesandbox reproduction with this issue?

**Comment by imbhargav5** [comment]
I tried a reproduction here. It does work. 
[![Edit m73jxqmy9x](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m73jxqmy9x)

**Comment by fhellwig** [comment]
I can do that but if you look at Dan's post, he shows how not keeping the callback using a ref (useRef) will cause this bug. Basically, his "won't work" example is the current rooks implementation. :-)

There is another package, react-useinterval, has the correct implementation (copied, and he acknowledges this, from the Abramov post).

**Comment by imbhargav5** [comment]
In the same article, Dan mentions that using `useReducer` like we did is also one of the solutions. Let me know if there is something that I am missing.

**Comment by imbhargav5** [comment]
Hmm, I see. I actually like the `useReducer` style better though. You are welcome to send a PR. Would be happy to add you to the list of contributors.

**Comment by fhellwig** [comment]
In your sandbox, just add `console.log('count', count)` after the dispatch (after line 13) and observe that count is *always* zero.

**Comment by imbhargav5** [comment]
Ah, you are right!

**Comment by fhellwig** [comment]
Even if I were to send you a pull request, I would simply be copying the code from Dan's post but I am sure you can do that just as well as me. :-) Thanks for curating all of these packages - very handy to have them all in one place!

**Comment by imbhargav5** [comment]
Sure that's no problem at all. Go ahead! And thank you for the compliments!

**Comment by imbhargav5** [comment]
I want to involve as many people as I can in this project. So if you can send a PR that would mean a lot!

**Comment by fhellwig** [comment]
I will send you a PR.

**Comment by imbhargav5** [comment]
@fhellwig This has been fixed and released in v3! Please take a look when you get chance.
