### ISSUE TITLE
useThrottle example not working

### ISSUE THREAD

**Issue by robations** [imbhargav5/rooks#501]
**Describe the bug**
When typing in the input of the useThrottle example, the "throttle value" remains empty.

I tried adjusting the code example, but wasn't really sure what the expected values were or to find a fix.

Console warning:

```
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
p
div
App@https://t0qql.csb.app/src/App.js:26:41
```

**To Reproduce**
1. Go to https://react-hooks.org/docs/usethrottle/#codesandbox-example
2. Type in input "abcdef"
3. Actual value updates, but throttle value doesn't
4. Warning (above) in console

**Expected behavior**

Guessing the throttle value should echo the actual value after a 1 second delay.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 89

Also reproduced issue with Chrome (Mac).

**Comment by imbhargav5** [comment]
Hi @robations Apologies for the delay. Was a bit caught up with work. I will get to them this weekend. Thank you!

**Comment by robations** [comment]
No problem, I know the feeling.

**Comment by imbhargav5** [comment]
Fix is WIP. It will be out in a couple of days. Thank you

**Comment by qiweiii** [comment]
@imbhargav5 I have looked at the example, the hook should be working fine, but the sandbox example is not using useThrottle correctly. My updated example is below:

```js
import React, { useState, useRef } from "react";
import { useThrottle } from "rooks";

function App() {
  const [text, setText] = useState("");
  const [throttleValue, setThrottleValue] = useState("");
  const [throttledFn, isReady] = useThrottle(changeThrottleValue, 1000);
  const ref = useRef(null);

  function changeThrottleValue() {
    setThrottleValue(ref.current.value);
  }

  return (
    <div>
      <h1>Rooks : useThrottle example</h1>
      <input
        ref={ref}
        onChange={(e) => {
          setText(e.target.value);
          if (isReady) throttledFn();
        }}
      />
      <p>Actual value: {text}</p>
      <p>
        Throttled value (being updated at most once per second): {throttleValue}
      </p>
    </div>
  );
}

export default App;
```

Please try it out
