### ISSUE TITLE
Missing fullscreen options

### ISSUE THREAD

**Issue by AdrienLemaire** [imbhargav5/rooks#505]
**Describe the bug**
The fullscreen hook options are missing [navigationUI](https://developer.mozilla.org/en-US/docs/Web/API/FullscreenOptions/navigationUI)
```ts
declare type FullScreenOptions = {
    onChange?: OnChangeEventCallback;
    onError?: EventCallback;
};
```

**Expected behavior**
[FullscreenOptions](https://developer.mozilla.org/en-US/docs/Web/API/FullscreenOptions) should be supported

**Additional context**
<details><summary>not working</summary>

As a temporary workaround, we can cast an overridded type to useFullscreen.

```ts
type ExtendedFullscreenOptions = Parameters<typeof useFullscreen>[0] & {
  // https://developer.mozilla.org/en-US/docs/Web/API/FullscreenOptions/navigationUI
  navigationUI?: "hide" | "show" | "auto";
};
interface IuseFullscreen {
  (options?: ExtendedFullscreenOptions): ReturnType<typeof useFullscreen>;
}

const MyComponent: React.FC = () => {
  const fullscreenApi = (useFullscreen as IuseFullscreen)({
    navigationUI: "hide", // Hide the Android bottom menu
  });

  return;
}
```

</details>

Options should be passed to requestFullscreen, but rooks isn't passing anything
https://github.com/imbhargav5/rooks/blob/main/src/hooks/useFullscreen.ts#L162

**Comment by imbhargav5** [comment]
Oh. You are right 🔥 Would you like to try a PR? I can do one this weekend if time permits. Thanks man!

**Comment by imbhargav5** [comment]
Fix is WIP. It will be out in a couple of days. Thank you
