### ISSUE TITLE
All hooks @rooks/use-xxx are missing  type definitions

### ISSUE THREAD

**Issue by nghiepit** [imbhargav5/rooks#524]
**Describe the bug**
All hooks @rooks/use-xxx are missing type definitions.
Example: https://www.npmjs.com/package/@rooks/use-interval
```json5
// package.json
{
  "main": "lib/index.js",
  "jsnext:main": "lib/index.esm.js",
  "module": "lib/index.esm.js",
  "types": "dist/types/key-ref/index.d.ts" <== INCORECT
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/54924428/127026839-1492e0a5-1399-4e19-8414-0a069e791de8.png)
![image](https://user-images.githubusercontent.com/54924428/127026957-ca50548c-2b70-4aea-bb10-765ca8269bcd.png)

**Comment by imbhargav5** [comment]
Hi @nghiepit , I understand that this is an issue but the package was in it's early days back then and we didn't have too many types. But `rooks` has types and you can start using that instead.
