### ISSUE TITLE
Convert helpers to typescript

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#525]
We have a few scripts which help us maintain our package. 

1. Convert helpers/** files to typescript
2. Change their usage in package.json which is currently `node helpers/... ` to work with the new typescript files

**Comment by maciekgrzybek** [comment]
I'll pick it up 👌

**Comment by maciekgrzybek** [comment]
Question - are all these scripts actually being used somewhere? For example, I can't find `update_readme` being used anywhere/
