### ISSUE TITLE
useMutationObserverRef documentation does not show example of using useMutationObserverRef

### ISSUE THREAD

**Issue by cg-n** [imbhargav5/rooks#529]
**Describe the bug**
The [documentation for `useMutationObserverRef`](https://react-hooks.org/docs/usemutationobserverref/) does not have an example of how to use `useMutationObserverRef`.

**To Reproduce**
1. Go to https://react-hooks.org/docs/usemutationobserverref/
2. Scroll to the Usage section
3. Look through the code

**Expected behavior**
The usage code sample has at least one mention of `useMutationObserverRef`.

**Actual behavior**
The usage code sample does not have any mention of `useMutationObserverRef`.

This is observed in rooks v5.4.2.

**Comment by imbhargav5** [comment]
Great catch @cg-n ! Would you like to submit a PR? You are welcome to give it a shot. No compulsion though. Thanks for submitting this issue!

**Comment by cg-n** [comment]
Thank you. Unfortunately I do not have time to commit to this at the moment.
