### ISSUE TITLE
useOutsideClickRef doesn't detect node changes

### ISSUE THREAD

**Issue by AdrienLemaire** [imbhargav5/rooks#530]
**Describe the bug**
When the node ref used by useOutsideClickRef re-renders or if its children change, clicking within a new element in that node will trigger useOutsideClickRef's callback.

**To Reproduce**
1. Open a menu used as ref by useOutsideClickRef
2. click on an icon in the menu that will replace said icon with a new one (in my case a button to toggle on/off sound)
3. click on the new icon => useOutsideClickRef callback triggered (in my case, incorrectly closes the menu).

**Expected behavior**
useOutsideClickRef memoizedCallback should rebuild the callback when the node is replaced or mutated.
Maybe using useMutationObserverRef would be the solution.

**Comment by imbhargav5** [comment]
@AdrienLemaire Will do this on top priority. Could you help us with a code sandbox? That would be super useful.

**Comment by AdrienLemaire** [comment]
@imbhargav5 as a temporary solution, I'm returning both icons, and toggling the hidden css style, so this is not urgent to me.

Sorry, I've finished my week and have to go. Tried to do a sandbox here, but the result is a bit different  (clicking on the button at any time will throw the alert)
https://codesandbox.io/s/useoutsideclickref-forked-m4ztt?file=/src/App.js

**Comment by imbhargav5** [comment]
@qiweiii can you check this out?

**Comment by qiweiii** [comment]
@imbhargav5 Got it, I'll take a look at it soon

**Comment by imbhargav5** [comment]
can you check if the latest version fixes your issue @AdrienLemaire ?

**Comment by imbhargav5** [comment]
Closing this for now but feel free to reopen.
