### ISSUE TITLE
`useMapState.spec.tsx` has duplicate title tests

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [imbhargav5/rooks#539]
**Describe the bug**
There are two tests with the title `should update old value correctly`.

**To Reproduce**
1. Run eslint on `useMapState.spec.tsx`
2. See error

**Expected behavior**
All tests have unique titles which accurately describe the test.

**Screenshots**
![image](https://user-images.githubusercontent.com/52586855/127748712-b1b04e21-f2ff-4e94-ae79-5d60d9987e12.png)

Version: `main` branch

**Comment by imbhargav5** [comment]
Good catch. @ChocolateLoverRaj . Do you want to try submitting a PR?

**Comment by ChocolateLoverRaj** [comment]
@imbhargav5 sure I will start a PR
