### ISSUE TITLE
Show contributors on home page

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#546]
So we need to generate a contributors.md inside the docusaurus package using all contributors cli within our script.

We can use the same script to update our readme.

**Comment by qiweiii** [comment]
@imbhargav5 I did not find `all contributors cli` in our project, do you mean using the contributors.yml in `.github/workflow`, and where do we put this contributors page in docusaurus?

**Comment by imbhargav5** [comment]
Yes `all contributors cli` doesn't seem to be as thorough as I thought. Let's just use contributors.yml in the workflow to generate another doc and put in the last section in the home page of our website.

**Comment by imbhargav5** [comment]
On second thought, it will be great if we just add it to our `ci-release.yml` workflow and just recreate it on each release. 
I am thinking we should just use  contributors from `github` rather than all contributors. What do you think?

**Comment by imbhargav5** [comment]
On third thought, let's use all contributors and keep it simple. What we should however do is to generate a `markdown` file on each release that we will use in our home page to show all contributors.

**Comment by qiweiii** [comment]
@imbhargav5 how do i know who are the maintainers?
