### ISSUE TITLE
Add Web OTP hook

### ISSUE THREAD

**Issue by ali-master** [imbhargav5/rooks#561]
**Is your feature request related to a problem? Please describe.**
Google Chrome has added the [Web otp](https://web.dev/web-otp/) feature and now, we can add it to this project.

**Describe the solution you'd like**
I would like to add this feature as a React hook to make it more simple for use in modern projects.

**Describe alternatives you've considered**
There is no alternative as I know.

What do you think? Is it that time to see the Web OTP feature in this project?

**Comment by qiweiii** [comment]
Sounds great! @ali-master go ahead!

**Comment by imbhargav5** [comment]
Yes!! @ali-master This sounds insane. Let's do it! Take a shot and we will also chip in.
