### ISSUE TITLE
Better Typescript : Use native types than creating a new one 

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#568]
https://github.com/imbhargav5/rooks/blob/85168bafc72033d3fcb8905959a49fcdbaaf2484/src/hooks/useWindowSize.ts#L4

**Comment by qiweiii** [comment]
Remove unnecessary extra type:
https://github.com/imbhargav5/rooks/blob/85168bafc72033d3fcb8905959a49fcdbaaf2484/src/hooks/useInput.ts#L3

Use native types here:
https://github.com/imbhargav5/rooks/blob/85168bafc72033d3fcb8905959a49fcdbaaf2484/src/hooks/useGeolocation.ts#L3
https://github.com/imbhargav5/rooks/blob/85168bafc72033d3fcb8905959a49fcdbaaf2484/src/hooks/useFullscreen.ts#L12
