### ISSUE TITLE
v6

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#587]
Priorities for v6.

- Typescript, Typescript and Typescript
- Deprecating packages which solve the same purpose. (useVisibilitySensor can be deprecated in favour of useInViewRef) etc
- useGeolocation, useFullscreen, 
- useCountdown should be deprecated, it makes sense for it to be in a hook for `dayjs`

v7 rough priorities
- form hooks
- accessibility

**Comment by qiweiii** [comment]
Hooks to be deprecated:

- `useInterval`: `useIntervalWhen` does the same job and has more features
- `useUpdateEffect`: similar to useDidUpdate
- `useVisibilitySensor`: `useInViewRef` has the same feature, may choose one of them
- `useSessionstorageState`: usage is the same as `useSessionstorage`

**Comment by imbhargav5** [comment]
@qiweiii Let's add deprecation message to all these? Lets add a dev only warning message in the console for these hooks and also add a deprecation label for docusaurus on the sidebar.

**Comment by nghiepit** [comment]
For `useToggle`: The 2nd argument should be a tuple value i.e ['dark', 'light'] instead of toggle function.

```ts
const [value, toggle] = useToggle('dark', ['light', 'dark']);

toggle(); // -> value == 'light'
toggle(); // -> value == 'dark'

// You can force specific value, in this case state will be set to given value
toggle('dark'); // -> value == 'dark'
```
Implemention
```ts
import { useState } from 'react';

function useToggle<T>(initialValue: T, options: [T, T]) {
  const [state, setState] = useState(initialValue);

  const toggle = (value?: React.SetStateAction<T>) => {
    if (typeof value !== 'undefined') {
      setState(value);
    } else {
      setState((current) => {
        if (current === options[0]) {
          return options[1];
        }

        return options[0];
      });
    }
  };

  return [state, toggle] as const;
}
```
Addtional `useBoolean`
```ts
function useBoolean(initialValue = false) {
  return useToggle(initialValue, [true, false]);
}
```
