### ISSUE TITLE
useMediaMatch doesn't work in Safari 13.1

### ISSUE THREAD

**Issue by krijoh92** [imbhargav5/rooks#590]
**Describe the bug**
Safari 13.1 doesn't support matchMedia's `addEventListener`, it uses the deprecated `addListener` instead. It's documented [here](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener#browser_compatibility):

> Prior to Safari 14, MediaQueryList is based on EventTarget, so you must use addListener() and removeListener() to observe media query lists.

I have tested a modified `useMediaMatch` where it uses `addListener` instead of `addEventListener` on Safari 13.1 and can submit a PR for it. 

**To Reproduce**
It is unfortunately hard to test to verify that it works. I used browserstack to use a Safari 13.1 browser. 

**Screenshots**
Screenshot of error from Safari 13.1
![image](https://user-images.githubusercontent.com/1156014/133034860-9c04d2cf-550b-49ac-be98-44a7a31974d3.png)

**Desktop (please complete the following information):**
 - OS: OSX Catalina
 - Browser Safari
 - Version 13.1

**Comment by imbhargav5** [comment]
@krijoh92 Thanks for creating this issue. 
> I have tested a modified useMediaMatch where it uses addListener instead of addEventListener on Safari 13.1 and can submit a PR for it.

Yes please!

**Comment by krijoh92** [comment]
Sweet, PR will be up in a bit👍

**Comment by krijoh92** [comment]
Thanks a lot for being so quick about resolving this issue :) !
