### ISSUE TITLE
useFocus / useFocusWithin

### ISSUE THREAD

**Issue by equinusocio** [imbhargav5/rooks#592]
**Is your feature request related to a problem? Please describe.**
An hook to detect if element has focus within and outside would be useful for accessibility, like the `:focus-within` css selector.

**Describe the solution you'd like**
Something like this:
https://react-spectrum.adobe.com/react-aria/useFocusWithin.html

**Describe alternatives you've considered**
Using the react-aria hooks

**Comment by equinusocio** [comment]
This hook is the only thing preventing me to drop react-aria dependency☹️

**Comment by imbhargav5** [comment]
Sorry @equinusocio for the delay. This will be ready in less than 2 weeks. Actively working on rooks right now. Thanks for your patience and understanding!

**Comment by equinusocio** [comment]
Good! Any update?

**Comment by equinusocio** [comment]
Any update on this?

**Comment by qqpann** [comment]
@imbhargav5 I tried this a bit. Can I take over it?

**Comment by imbhargav5** [comment]
@qqpann Go for it!
