### ISSUE TITLE
useTimeout restart() method that does not cause a state update

### ISSUE THREAD

**Issue by LoganDark** [imbhargav5/rooks#594]
**Is your feature request related to a problem? Please describe.**
I'm setting a timeout as a result of a user action that saves to file in 2000 ms, that way, if multiple actions are performed in a small period, the disk doesn't get thrashed. However, the state updates required to clear and start the timer are taking upwards of 50 ms. This causes noticeable sluggishness in the application, even though I'm only scheduling a save to eventually happen in the future.

**Describe the solution you'd like**
Add a `restart` method to the returned object, that doesn't cause any state updates if the timeout is already started.

**Describe alternatives you've considered**
I'm going to have to stop using `useTimeout` now since it causes too much of a performance issue

**Additional context**
Since this is serializing the state of a code editor, 50ms freezes are happening on scroll, on cursor movement, selection, etc. If a desktop application can't even maintain 60fps then I don't know what I'm doing with my life.

**Comment by imbhargav5** [comment]
@LoganDark Could you help with a snippet? I will make sure we find a solution to this before Monday.

**Comment by LoganDark** [comment]
> @LoganDark Could you help with a snippet? I will make sure we find a solution to this before Monday.

I can't, as it's all proprietary. I'm sure the sluggishness of the state updates depends on how complex the host component is. So, all you need is to `useTimeout` in a complex component, and then clear and start it on every user interaction, i.e. scroll or keydown in an input field. Then you will feel the slowness

**Comment by imbhargav5** [comment]
@LoganDark Could you try using `useTimeoutWhen` instead? We are deprecating `useTimeout` anyway. That should be very easy to use in this case, as you will have to manage a boolean and that will start/stop the timeout based on the boolean.

**Comment by LoganDark** [comment]
> That should be very easy to use in this case, as you will have to manage a boolean and that will start/stop the timeout based on the boolean.

In order to restart the timer, I would still have to do 2 state updates.

Aren't you only deprecating useInterval?

**Comment by imbhargav5** [comment]
No, there are a few that we are deprecating since we have better alternatives. A PR for that will be in the works so the message about which hooks are deprecated will be clear. 

https://github.com/imbhargav5/rooks/issues/587#issuecomment-918226825

**Comment by LoganDark** [comment]
> No, there are a few that we are deprecating since we have better alternatives. A PR for that will be in the works so the message about which hooks are deprecated will be clear.
> 
> [#587 (comment)](https://github.com/imbhargav5/rooks/issues/587#issuecomment-918226825)

Yes, that is _exactly_ where I got the information that useInterval would be deprecated. It looks like you've just realized you forgot to also list useTimeout.

**Comment by imbhargav5** [comment]
> Yes, that is exactly where I got the information that useInterval would be deprecated. It looks like you've just realized you forgot to also list useTimeout.

Yes. It was another maintainers comment. I modified that and pasted a link so you can see other hooks which are also being deprecated. We are trying to improve rooks actively. 

> It looks like the new hooks, being API-less, don't even have the space to include a feature like this. Which results in the same situation since changing when is now the only way to reset the timer, and you still need two state updates to do so. It's just now, there's nowhere to add a reset feature.

If you set when to false, the timer is off. Either way to help you out we need a snippet that explains the requirements better. Any code snippet that is similar to what you want will do.

**Comment by imbhargav5** [comment]
If this hook won’t solve the problem we will try to come up with changes or just an entirely new hook. We just need to see the intended scenario more from your perspective.

**Comment by LoganDark** [comment]
> If you set when variable to false, the timer is off.

By reset, I meant restart, sorry. I don't mean stop the timer. In order to _restart_ the timer, you have to first cause a state update where `when` is false, and then cause a state update where it is true. In the end, `when` is still true and the timer is still active. But the fact that two state updates have to be performed causes React to have to re-render twice which is very slow (in my case 25ms per render).

> Either way to help you out we need a snippet that explains the requirements better. Any code snippet that is similar to what you want will do.

Sure, I can provide a code example for those requirements:

```js
const api = useTimeout(<saving to filesystem>, 2000);

function onUserInteraction() { // called on scroll, click, etc. CAN NOT take more than a few milliseconds
    // Restart the timeout, so that 2 seconds after the last interaction, stuff is saved
    api.clear(); // state update
    api.start(); // state update
    // we only NEED a maximum of 1 state update, and that's if the timeout is inactive to start with
}
```

I'm just using a timeout to save to the filesystem two seconds after the last interaction. To do this I need to restart the timeout on each interaction so that it doesn't trigger while the user is still interacting.

Hopefully the code sample communicates it a bit better.

**Comment by LoganDark** [comment]
> If this hook won’t solve the problem we will try to come up with changes or just an entirely new hook. We just need to see the intended scenario more from your perspective.

Come to think of it, it looks like you already have a debounce hook of some kind. However, there's no useful documentation on it and I don't know what it does or if it serves this use case. The only documentation I can find is:

```jsx
function Demo() {
  useDebounce();
  return null;
}

render(<Demo />);
```

which is not very informative.

**Comment by imbhargav5** [comment]
Yes. useDebounce probably won't solve your issue.

**Comment by imbhargav5** [comment]
@LoganDark Will this not solve your problem? 🤔 

```jsx
function m({writeToDisk}){
   const debouncedWriteToDisk = useDebounce(writeToDisk, 2000) 
   
   return <button onClick={debouncedWriteToDisk}>WriteToDisk</button> 
}
```

**Comment by LoganDark** [comment]
> @LoganDark Will this not solve your problem? 🤔
> 
> ```js
> function m({writeToDisk}){
>    const debouncedWriteToDisk = useDebounce(writeToDisk, 2000) 
>    
>    return <button onClick={debouncedWriteToDisk}>WriteToDisk</button> 
> }
> ```

No, because this isn't saving from a manual button click, it's saving automatically code that hasn't yet been explicitly saved by the user

**Comment by imbhargav5** [comment]
@LoganDark You can call the denounced callback when the user stops typing or on a button click or whenever. 

That should do the job IMO.

**Comment by LoganDark** [comment]
> @LoganDark You can call the denounced callback when the user stops typing or on a button click or whenever.
> 
> That should do the job IMO.

Right, and now we're back to the problem of "how do we know when the user is done typing". I only get events on each key down. There's no event for "there have been no keys down in the past couple seconds". So I have to use a timeout.

**Comment by imbhargav5** [comment]
I think I have a solution for this. I will get back in a day.

**Comment by LoganDark** [comment]
I no longer need this feature, but just for completeness, is the issue just closed or is there a solution in Rooks now? ty
