### ISSUE TITLE
List of possible keys

### ISSUE THREAD

**Issue by mmahalwy** [imbhargav5/rooks#605]
Would be great to get an idea of all the possible keys or have it typed in TS

**Comment by hufftheweevil** [comment]
I think the OP was asking for documentation on the possible values for the `keyList` argument of the `useKey`, `useKeys` and `useKeyRef` hooks. I, too, am looking for this information.

**Comment by hufftheweevil** [comment]
After reviewing the code, I see that it will basically accept any `e.key`, `e.code`, `e.keyCode`, `e.which`, or `e.charCode`. Perhaps this should be explained in the docs somewhere.

**Comment by imbhargav5** [comment]
Got it. So the actionable item here is to improve documentation of keyboard related hooks like `useKey`, `useKeys` and `useKeybindings.`
