### ISSUE TITLE
Return array instead of object for useInterval hook

### ISSUE THREAD

**Issue by chattling** [imbhargav5/rooks#64]
**Is your feature request related to a problem? Please describe.**
I would like to be able to give my own names for start and stop functions returned by useInterval hook. It is possible to use object renaming like { start: myStartFunc } with current implementation, however it would be more inline with react hooks to have them returned as array for easier renaming.

**Describe the solution you'd like**
Return start, stop, intervalId in array instead of in object.

**Describe alternatives you've considered**
See above

**Additional context**
N/A

**Comment by imbhargav5** [comment]
Sounds good to me!

We should make it return an array to support array destructuring while maintaining backward compatibility with object destructuring. 

Would love it if you can send a PR!

**Comment by chattling** [comment]
I know how to change it by returning array instead of object, but I can't think of way to make it backward compatible without creating whole new hook.
Also I don't feel comfortable opening PR, as I never done it before..

**Comment by imbhargav5** [comment]
It's fine if you are new to it and it's difficult. But you can use my repo as a playground for a PR. I don't mind if it's not the best PR. Most of mine aren't. It's not a compulsion though. :)

**Comment by imbhargav5** [comment]
It's coming in an upcoming release.
