### ISSUE TITLE
Containment property not working / usage unclear

### ISSUE THREAD

**Issue by brtdv** [imbhargav5/rooks#66]
Hi guys,
I'm trying to use the `containment` property in the options object of the `useVisibilitySensor` hook, but the `containment` property does not seem to work (or I'm using it wrong?)

Please consider the example at: **https://codesandbox.io/s/falling-hooks-orwyw?fontsize=14**.

When you use your browsers' inspect element on Box 0, you'll see that the `isVisible` class is only removed when the Box moves out of the `window` viewport. However, I've passed the `Container` element as the `containment` property, so I expect the `isVisible` class/property to be false when the item moves out of view in the `Container` box. I'm not sure if I use the `containment` property in a wrong way or if this is a bug...

See also the following screenshot: 
<img width="1440" alt="Screenshot 2019-05-21 at 21 47 42" src="https://user-images.githubusercontent.com/932365/58126644-ae2e3f00-7c13-11e9-837a-8ac4c194a92f.png">

The inspected `.Box` element has moved out of the viewport of the `Container` that is passed to the `containment` property, but still receives `isVisible: true`...

I'm able to simulate this problem on Google Chrome (Version 74.0.3729.157 (Official Build) (64-bit)) on Mac, but I'm also able to simulate the problem on Safari and Firefox.

Do you guys have any feedback on what is going wrong in this code? Or is this effectively a bug related to the `containment` property?

**Comment by imbhargav5** [comment]
@brtdv Thanks for taking the time to make a sandbox and bringing up this issue. On first impression, it does seem like a bug to me. Taking a look now.

**Comment by imbhargav5** [comment]
Seems like `position:absolute` is causing this issue. 
https://codesandbox.io/s/mystifying-wildflower-3z628?fontsize=14

This is the expected behaviour right?

**Comment by brtdv** [comment]
> Seems like `position:absolute` is causing this issue.
> https://codesandbox.io/s/mystifying-wildflower-3z628?fontsize=14
> 
> This is the expected behaviour right?

Yes, this example has the expected behaviour, but I'm not sure if `position: absolute;` is the cause of the problem. The example now has the expected behaviour, but probably because the `.Box` elements move out of the `window` instead of out of the `containment` element.

**Comment by brtdv** [comment]
I was able to find a solution. The problem is not the code around the `containment` property in the library itself, but rather my demo apps' hooks usage/container initialization.

The key is that the <Box /> elements can only be rendered after the `containerRef` has been fullfilled to get my demo working... This is a bit tricky with hooks, but I've managed to 'hack' together a solution by using `useEffect` to force a 2nd re-render of the `Container`, after the `containerRef` has been filled... I'm not sure if this is the most elegant solution though? 

I checked the [React useRef docs](https://reactjs.org/docs/hooks-reference.html#useref), there's plenty of demo code for using refs in event handlers but no clear 'best practice' demo when you need to use a ref, on initialization, in another hook...

See also updated sandbox at: https://codesandbox.io/s/cold-wildflower-btfo1?fontsize=14

```jsx
export default function Container(props)
{
  const containerRef = useRef(null);
  const [forceRender, updateForceRender] = useState(false);

  useEffect(() => {
    // After 1st render, force a 2nd render
    // In the 2nd render, the 'containerRef' variable will be filled,
    // and the <Box /> components will be rendered...
    updateForceRender(true);
  }, []);

  const [allIndexes, setallIndexes] = useState([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14]);

  return (
    <div className="CenterContainer" ref={containerRef}>
      {(!!containerRef && !!containerRef.current) && // Render <Box /> components only after the containerRef is fullfilled!
        allIndexes.map(index => (
          <Box containerRef={containerRef} key={index} index={index} />
        ))
      }
    </div>
  );
}

```

**Comment by imbhargav5** [comment]
@brtdv Ahh. I see. But I think we should come up with a solution that doesn't need this from the end user. What if this hook supported a ref as a containment. So, something like containmentRef or something?

**Comment by brtdv** [comment]
@imbhargav5 Yeah, absolutely, that seems like a more elegant solution...

**Comment by imbhargav5** [comment]
Would you like to give it a shot?

**Comment by simbathesailor** [comment]
Hello guys, I am working on useIntersectionObserver, which can work the same as "useVisibility"  hook. 

More pointer here for the benefits of using intersectionObserver: 
https://github.com/imbhargav5/rooks/issues/22#issuecomment-498124498

@brtdv I forked your repo and tried it with useIntersectionObserver. Could you please have a look at the forked code sandbox link(https://codesandbox.io/s/autumn-butterfly-cc2qb) in which I have used useIntersectionObserver. Does that work as expected? 


Here is the pr, feel free to tell me, if anything can be done in a better way. 

https://github.com/imbhargav5/rooks/pull/69
