### ISSUE TITLE
useMutationObserver disconnect

### ISSUE THREAD

**Issue by devagja** [imbhargav5/rooks#666]
Hello,
I can't find a way to disconnect the observer on the callback, it would be great to be able to do that.

Thank you

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/disconnect

**Comment by imbhargav5** [comment]
The `disconnect` happens within the `useEffect` cleanup internally. Do you have a particular use case in mind?

**Comment by bojanvidanovic** [comment]
What if I want to observe an element only once? I think there should be a 3rd prop like `once` (boolean) which would disconnect the observer once it's visible.
