### ISSUE TITLE
Create a better Readme

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#7]

**Comment by bradd123** [comment]
What do you mean by `better` here? Can you please describe so that I can contribute?

**Comment by imbhargav5** [comment]
👋 @bradd123. So right now, the Readme.md in the root of the project is auto generated by combining readme across all the `hook` packages. I am thinking we can improve that and take it further. Some of my ideas are like this

- [ ] Add inspiration for this project. 
- [ ] Expanding the list of features
- [ ] Links to other the readme's of the packages instead of just putting it all out in the main Readme.
- [ ] Link to Contributing.md and also adding a more detailed guide to Contributing.md for developers to get started with. 

Let me know if you have more ideas around this!
