### ISSUE TITLE
MutableRefObject<HTMLElement> in useBoundingClientRect

### ISSUE THREAD

**Issue by JustinLivi** [imbhargav5/rooks#70]
Thanks for developing this library! I'm just diving into hooks but this seems like a great resource.

**Describe the bug**
Currently the `useBoundingClientRect` hook expects a `MutableRefObject<HTMLElement>`.

Based on the behavior and typings for `useRef` from the DefinitelyTyped definitions for React, producing a `MutableRefObject<HTMLElement>` does not appear to be possible.

The closest I can get is a `MutableRefObject<HTMLElement | null>` element which I think should be the expected input type.

**To Reproduce**
The following code will reproduce the behavior:
```typescript
const ref = useRef<HTMLElement | null>(null);
const boundingclientrect = useBoundingClientRect(ref);
```

Error Produced:
```
Argument of type 'MutableRefObject<HTMLElement | null>' is not assignable to parameter of type 'MutableRefObject<HTMLElement>'.
  Type 'HTMLElement | null' is not assignable to type 'HTMLElement'.
    Type 'null' is not assignable to type 'HTMLElement'.ts(2345)
```

Using the following library versions:
- @types/react@16.8.23 
- @rooks/use-boundingclientrect@3.0.1
- typescript@3.5.2

**Additional context**
See the following issue on DefinitelyTyped for an in-depth discussion of the various typings for the output of `useRef` and why it appears `MutableRefObject<HTMLElement | null>` is the correct typing for the use-case.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31065

Note: It's easy to work around this using `any` but I thought I'd open an issue because having accurate typings is always great!

**Comment by imbhargav5** [comment]
Ahh you are right! Sorry, I am responding late. Would you like to submit a PR? That would be great!

**Comment by imbhargav5** [comment]
@JustinLivi Just made this fix. Will publish shortly!

**Comment by JustinLivi** [comment]
Thanks! Sorry I didn't get around to submitting a PR.

**Comment by imbhargav5** [comment]
Np! Thanks for helping me identify this issue!
