### ISSUE TITLE
`useLocalstorage` does not use the defaultValue on the first render

### ISSUE THREAD

**Issue by ndeviant** [imbhargav5/rooks#734]
**Describe the bug**
The `useLocalstorageState` does not have this issue, as far as I could tell.

**To Reproduce**
https://codesandbox.io/s/uselocalstorage-forked-jm7t6?file=/src/App.js
1. Make sure you localStorage has no "name" field in it
2. Watch the console

**Expected behavior**
Should use default value on the first render.

**Screenshots**
<img width="1219" alt="Screenshot 2021-12-13 at 19 26 17" src="https://user-images.githubusercontent.com/25330222/145860013-22226ee1-be09-4db9-a0a0-9ead181ac7d9.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 95.0.4638.54 (Official Build) (x86_64)

**Additional context**

**Comment by Goku-kun** [comment]
Hello @imbhargav5.
Is anyone working on this? I'd like to take a stab at solving this issue.

**Comment by gpoole** [comment]
The default value is set by a [`useEffect`](https://github.com/imbhargav5/rooks/blob/17f48f0a1e69f4688d3644d00a024257f3f57004/src/hooks/useLocalstorage.ts#L82), so it'll only ever be available in the second render. The hook will need to return the default instead of `value` if `value` is `null` for it to work in the first render.

**Comment by imbhargav5** [comment]
@gpoole go for it! I get what you are saying!

**Comment by imbhargav5** [comment]
@gpoole also before you try it , could you see if uSeLocalStorageState solves your problem? I made some poor api choices with useLocalstorage and I am planning to deprecate it in favor of the new hook.

**Comment by gpoole** [comment]
@imbhargav5 oh I didn't realise there was `useLocalStorageState`. API looks good to me and looks like that won't have the same bug either so deprecating `useLocalStorage` sounds like the best option.
