### ISSUE TITLE
useSessionstateStorage does not re-render when removing item from storage

### ISSUE THREAD

**Issue by LongLiveCHIEF** [imbhargav5/rooks#780]
**Describe the bug**
The `useSessionstateStorage` docs read:

> useState but syncs with sessionstorage

This implies that any change implemented with this hook will cause a re-render. At the moment, using the remove function does not cause the component to re-render.

If this is desired behavior, we should document it. 

If we want it to re-render (which makes sense to me), then I can look into making a PR.

**Comment by LongLiveCHIEF** [comment]
I should have a PR coming in shortly for this.

**Comment by imbhargav5** [comment]
I see this is a definite bug. Will take a look at your PR.

**Comment by imbhargav5** [comment]
Please try this in the latest version. A lot of the state related problems have been fixed.

**Comment by imbhargav5** [comment]
Feel free to reopen if this issue still exists.

**Comment by LongLiveCHIEF** [comment]
If I can tell what's going on based on your changes, there is a storage event listener that re-evaluates the `key` value when the `removeItem` changes the storage area?

I can't track in the code where this effect causes a change to state anywhere in the hook (thus causing a re-render). I can take a look when I'm back in the office.

I'm also worried that if it _does_ cause a re-render, it does so via a side-effect, meaning it would re-render with the cleared value _after_ a re-render due to the storage event changing the initialize state, thus causing a double re-render when a value is removed (or maybe even when it is changed in any way).

**Comment by imbhargav5** [comment]
🤔 We haven't had any reports on bugs on useSessionstorageState yet. But if there is a reproduction I can take look!
