### ISSUE TITLE
matchSelection on useSelectableList returns void

### ISSUE THREAD

**Issue by 3rma1** [imbhargav5/rooks#807]
Hello,

I am using useSelectableList  hook and I am noticing that it returns a void, instead of boolean.
const matchSelection: (parameters: OptionalIndexValue<Tags>) => void

On the documentation it says that it returns a boolean.
({ index?: number, value?: T }) => Boolean

**Comment by imbhargav5** [comment]
Ah if this is so, then this is probably a bug. Would love it if you can provide a reproduction in a sandbox.

**Comment by imbhargav5** [comment]
_Years later_

This should be fixed.
