### ISSUE TITLE
Re-exporting other hooks

### ISSUE THREAD

**Issue by wintercounter** [imbhargav5/rooks#82]
I had a similar idea to release a hooks library. I'd have some hooks also on my own that I want to release and it would be nice if I'd be able simply include them in `rooks`. Would you consider such solution (re-exporting 3rd party hooks)? There are definitely some nice hooks out there and I think it would make more sense reusing those than recreating the same.

**Comment by imbhargav5** [comment]
I don't mind copying open source code and making hooks from existing 3rd party hooks and potentially improving them but re exporting might be a bit of a grey area. Don't think it would look good on `rooks`. What do you think?

**Comment by wintercounter** [comment]
My initial idea was making a repo/package that is a collection hooks around npm. It would be a community effort, anyone can add his package/findings and `rooks` would fit into this imo. Otherwise I'll basically go and create such lib :) 
It would most probably also re-export hooks from rooks as well.

**Comment by imbhargav5** [comment]
Sure. Feel free to do that.
