### ISSUE TITLE
[useFullscreen] Return type appears incorrect

### ISSUE THREAD

**Issue by bthall16** [imbhargav5/rooks#877]
https://github.com/imbhargav5/rooks/blob/49e14919944b7755926644cc0af7a0c05ff61f1d/src/hooks/useFullscreen.ts#L150

The return type for the `useFullscreen` hook is of type `FullscreenApi | undefined`. However, looking through the function body I don't see any path where `undefined` is returned. Consequently, TypeScript users have to perform type checks or add non-null assertions, both of which are unnecessary.

**Comment by qqpann** [comment]
@imbhargav5 This seems to be already fixed.

**Comment by imbhargav5** [comment]
@qqpann Got it. Will close 👍
