### ISSUE TITLE
Create hook script is outdated

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#88]
The workflow we have to create a new package with `yarn run create` is outdated.

**Comment by maciekgrzybek** [comment]
What's wrong with it ?

**Comment by imbhargav5** [comment]
@maciekgrzybek 
I think this checking this list should be good. 

- [ ] We need src/index.ts and src/useHook.ts and the useHook should come from the hook name
- [ ] LICENSE is missing
- [ ] .npmignore is missing
- [ ] tsconfig.json is missing
- [ ] package.json is different. We can mimic it as closely as possible by taking another hook as example. eg `useInput`
- [ ] index.d.ts is not needed to be put in the directory anymore since it is autogenerated.
