### ISSUE TITLE
[useLocalStorageState] and [useSessionStorageState] should support replacer, reviver for JSON stringify and parsing.

### ISSUE THREAD

**Issue by imbhargav5** [imbhargav5/rooks#900]
**Is your feature request related to a problem? Please describe.**
Some users require saving objects like ES6 maps which can't be JSON.stringified without a replacer function. 

**Describe the solution you'd like**

We need replacer/ reviver functions optionally to be sent as arguments. 
```javascript
useLocalstorageState('key', value, {
  replacer: () => {},
  reviver: () => {} 
})

```
Replacer will be used by JSON.stringify and JSON.parse will use the reviver. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

What do you think?

**Comment by imbhargav5** [comment]
That would be great!!

**Comment by danditomaso** [comment]
Any progress on this issue?

**Comment by harshilparmar** [comment]
Sorry for late , but I would love to work on now and if you have bandwidth you can also take it if you want.
