### ISSUE TITLE
useMultiSelectableList matchSelection returns void rather than boolean

### ISSUE THREAD

**Issue by zethussuen** [imbhargav5/rooks#904]
**Describe the bug**
Using matchSelection on checkbox inputs complains in TypeScript due to `void` not being assignable to `boolean`

**To Reproduce**
1. Create a list of checkboxes using useMultiSelectableList
2. Set the checked prop of the inputs to matchSelection({ index })
3. See error

**Expected behavior**
matchSelection should return type boolean as TypeScript expects

**Screenshots**
<img width="448" alt="image" src="https://user-images.githubusercontent.com/754158/160292468-ad5b150e-5a8f-49fb-8543-888ee389a790.png">
<img width="892" alt="image" src="https://user-images.githubusercontent.com/754158/160292588-6891c75a-c383-4a16-b874-9e571249c3c8.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser Chrome
 - Version 99.0.4844.74

**Additional context**
Looking through the source it seems like it's always returned void? Am I missing something in my implementation?

**Comment by imbhargav5** [comment]
Should be fixed!
