### ISSUE TITLE
useGeolocation hook 

### ISSUE THREAD

**Issue by simbathesailor** [imbhargav5/rooks#92]
As discussed in https://github.com/imbhargav5/rooks/issues/36#issuecomment-505532787, creating the ticket for tracking the progress for "useGeolocation" hook.

Here is the initial prototype made .

https://codesandbox.io/s/usegeolocation-h2lim

I will try to raise a pr for this one, next week. Have a look and give feedback if any.

Thanks

**Comment by imbhargav5** [comment]
Beautiful!! This looks so good.

**Comment by imbhargav5** [comment]
One thing we should do is, we should not have any arguments of `geolocation` within our hook. They should be passed as is. 
So we shouldn't need to do `useGeolocation(a,b,c,opts)` and then `gelocation(a,b,c,opts)`. Instead it should be `useGeolocation(...hookSpecficArgs?,...geolocationargs)` => `geolocation(...geolocationargs)`

**Comment by simbathesailor** [comment]
Raised a pull request for useGeolocation hook.  
https://github.com/imbhargav5/rooks/pull/100

**Comment by imbhargav5** [comment]
Fixed with ff0052ef8e34b80a3909a0c37ed2520a184624bc
